### ISSUE TITLE
Spaceship: Exception in v0.24 when calling candidate_builds

### ISSUE THREAD

**Issue by czivko** [fastlane/fastlane#3889]
Given a valid app fetched from iTunes, 
Calling `puts app.edit_version.candidate_builds.first`
Raises the exception below.

This was working in v0.23

Fix:
When trying to inspect the apple_id for to_s in build.rb:128 self.build_train is null
This fixed it for me by just checking if self.build_train is set
```ruby
      def apple_id
        return @apple_id if @apple_id
        return self.build_train.application.apple_id if self.build_train
      end
```

NoMethodError: undefined method `application' for nil:NilClass
/spaceship-0.24.0/lib/spaceship/tunes/build.rb:130:in `apple_id'

**Comment by KrauseFx** [comment]
Is it your own spaceship script? If so please share the complete script and output when running it

**Comment by czivko** [comment]
@KrauseFx updated the issue above and tracked down the cause. when trying to print the build with a puts was causing the issue for me.

**Comment by lmirosevic** [comment]
Can confirm this in `0.24.0`, using the following simple code:

```ruby

    Spaceship::Tunes.login(@params['itc_account'], @params['itc_password'])
    app = Spaceship::Tunes::Application.find(@params['bundle_id'])
    version = app.edit_version
    builds = version.candidate_builds
    puts builds
```

**Comment by mfurtak** [comment]
Reproduced locally - thanks for the report, and thanks for the code! :+1: I'm looking into it.

**Comment by mfurtak** [comment]
Hi folks - we've released [`spaceship` 0.24.1](https://github.com/fastlane/fastlane/releases/tag/spaceship%2F0.24.1) with a fix for this. Please update and let us know if that fixes things for you! :+1: :rocket:

**Comment by lmirosevic** [comment]
Seems to work now. Thanks for the quick fix!
