### ISSUE TITLE
Fastlane should declare a maximum ruby version of 3.1

### ISSUE THREAD

**Issue by SMillerDev** [fastlane/fastlane#20980]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
Some of the dependencies don't work with ruby 3.2 (https://github.com/SlatherOrg/slather/issues/529) so fastlane shouldn't be installable with this ruby version

##### Command executed
`fastlane` anything with `slather`

##### Complete output when running fastlane, including the stack trace and command used
<details>
  <pre>
[09:53:21]: ------------------------------
[09:53:21]: Driving the lane 'ios metrics' 🚀
[09:53:21]: ---------------------
[09:53:21]: --- Step: slather ---
[09:53:21]: ---------------------
[09:53:21]: $ slather coverage --jenkins --sonarqube-xml --build-directory outputdata --output-directory ./sonar-reports --scheme **redacted**.xcodeproj
[09:53:21]: ▸ Slathering...
[09:53:21]: ▸ /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/slather-2.7.3/lib/slather/project.rb:506:in `find_binary_files': undefined method `exists?' for File:Class (NoMethodError)
[09:53:21]: ▸ raise StandardError, "No scheme named '#{self.scheme}' found in #{self.path}" unless File.exists? xcscheme_path
[09:53:21]: ▸ ^^^^^^^^
[09:53:21]: ▸ Did you mean?  exist?
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/slather-2.7.3/lib/slather/project.rb:456:in `configure_binary_file'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/slather-2.7.3/lib/slather/project.rb:336:in `configure'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/slather-2.7.3/lib/slather/command/coverage_command.rb:59:in `execute'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/clamp-1.3.2/lib/clamp/subcommand/execution.rb:18:in `execute'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:66:in `run'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/clamp-1.3.2/lib/clamp/command.rb:140:in `run'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/gems/slather-2.7.3/bin/slather:17:in `<top (required)>'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/slather:25:in `load'
[09:53:21]: ▸ from /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/slather:25:in `<main>'
[09:53:21]: ▸ undefined method `exists?' for File:Class
[09:53:21]: ▸ Are you sure your project is generating coverage? Make sure you enable code coverage in the Test section of your Xcode scheme.
[09:53:21]: ▸ Did you specify your Xcode scheme? (--scheme or 'scheme' in .slather.yml)
[09:53:21]: ▸ If you're using a workspace, did you specify it? (--workspace or 'workspace' in .slather.yml)
[09:53:21]: ▸ If you use a different Xcode configuration, did you specify it? (--configuration or 'configuration' in .slather.yml)
  </pre>
</details>

### Environment

[⠋] 🚀 Ignoring racc-1.6.2 because its extensions are not built. Try: gem pristine racc --version 1.6.2
[✔] 🚀
[10:17:11]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[10:17:11]: Generating fastlane environment output, this might take a few seconds...
swift-driver version: 1.62.15 <details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                        |
| --------------------------- | ------------------------------------------------------------ |
| OS                          | 13.1                                                         |
| Ruby                        | 3.2.0                                                        |
| Bundler?                    | false                                                        |
| Git                         | git version 2.39.0                                           |
| Installation Source         | /opt/homebrew/Cellar/fastlane/2.211.0_1/libexec/bin/fastlane |
| Host                        | macOS 13.1 (22C65)                                           |
| Ruby Lib Dir                | /opt/homebrew/Cellar/ruby/3.2.0/lib                          |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                                   |
| Is contained                | false                                                        |
| Is homebrew                 | true                                                         |
| Is installed via Fabric.app | false                                                        |
| Xcode Path                  | /Applications/Xcode_14.2.app/Contents/Developer/             |
| Xcode Version               | 14.2                                                         |
| Swift Version               | 5.7.2                                                        |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     |             |   |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.211.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version      |
| ------------------------------- | ------------ |
| error_highlight                 | 0.5.1        |
| did_you_mean                    | 1.6.3        |
| syntax_suggest                  | 1.0.2        |
| atomos                          | 0.1.3        |
| rexml                           | 3.2.5        |
| CFPropertyList                  | 3.0.5        |
| claide                          | 1.1.0        |
| colored2                        | 3.1.2        |
| nanaimo                         | 0.3.0        |
| xcodeproj                       | 1.22.0       |
| rouge                           | 2.0.7        |
| xcpretty                        | 0.3.0        |
| terminal-notifier               | 2.0.0        |
| unicode-display_width           | 1.8.0        |
| terminal-table                  | 1.8.0        |
| plist                           | 3.6.0        |
| public_suffix                   | 5.0.1        |
| addressable                     | 2.8.1        |
| multipart-post                  | 2.0.0        |
| word_wrap                       | 1.0.0        |
| optparse                        | 0.1.1        |
| tty-screen                      | 0.8.1        |
| tty-cursor                      | 0.7.1        |
| tty-spinner                     | 0.9.3        |
| artifactory                     | 3.0.15       |
| babosa                          | 1.0.4        |
| colored                         | 1.2          |
| highline                        | 2.0.3        |
| commander                       | 4.6.0        |
| excon                           | 0.96.0       |
| faraday-em_http                 | 1.0.0        |
| faraday-em_synchrony            | 1.0.0        |
| faraday-excon                   | 1.1.0        |
| faraday-httpclient              | 1.0.1        |
| faraday-multipart               | 1.0.4        |
| faraday-net_http                | 1.0.1        |
| faraday-net_http_persistent     | 1.2.0        |
| faraday-patron                  | 1.0.0        |
| faraday-rack                    | 1.0.0        |
| faraday-retry                   | 1.0.3        |
| ruby2_keywords                  | 0.0.5        |
| faraday                         | 1.10.2       |
| unf_ext                         | 0.0.8.2      |
| unf                             | 0.1.4        |
| domain_name                     | 0.5.20190701 |
| http-cookie                     | 1.0.5        |
| faraday-cookie_jar              | 0.0.7        |
| faraday_middleware              | 1.2.0        |
| fastimage                       | 2.2.6        |
| gh_inspector                    | 1.1.3        |
| json                            | 2.6.3        |
| mini_magick                     | 4.12.0       |
| naturally                       | 2.2.1        |
| rubyzip                         | 2.3.2        |
| security                        | 0.1.3        |
| xcpretty-travis-formatter       | 1.0.1        |
| dotenv                          | 2.8.1        |
| bundler                         | 2.4.2        |
| simctl                          | 1.6.8        |
| jwt                             | 2.6.0        |
| uber                            | 0.1.0        |
| declarative                     | 0.0.20       |
| trailblazer-option              | 0.1.2        |
| representable                   | 3.2.0        |
| retriable                       | 3.1.2        |
| mini_mime                       | 1.1.2        |
| memoist                         | 0.16.2       |
| multi_json                      | 1.15.0       |
| os                              | 1.1.4        |
| signet                          | 0.17.0       |
| googleauth                      | 1.3.0        |
| httpclient                      | 2.8.3        |
| webrick                         | 1.7.0        |
| google-apis-core                | 0.9.3        |
| google-apis-playcustomapp_v1    | 0.12.0       |
| google-apis-androidpublisher_v3 | 0.32.0       |
| google-cloud-env                | 1.6.0        |
| google-cloud-errors             | 1.3.0        |
| google-cloud-core               | 1.6.0        |
| google-apis-iamcredentials_v1   | 0.16.0       |
| google-apis-storage_v1          | 0.19.0       |
| rake                            | 13.0.6       |
| digest-crc                      | 0.6.4        |
| google-cloud-storage            | 1.44.0       |
| emoji_regex                     | 3.2.3        |
| jmespath                        | 1.6.2        |
| aws-partitions                  | 1.688.0      |
| aws-eventstream                 | 1.2.0        |
| aws-sigv4                       | 1.5.2        |
| aws-sdk-core                    | 3.168.4      |
| aws-sdk-kms                     | 1.61.0       |
| aws-sdk-s3                      | 1.117.2      |
| set                             | 1.0.3        |
| forwardable                     | 1.3.3        |
| logger                          | 1.5.3        |
| pathname                        | 0.2.1        |
| shellwords                      | 0.1.0        |
| cgi                             | 0.3.6        |
| date                            | 3.3.3        |
| timeout                         | 0.3.1        |
| securerandom                    | 0.2.2        |
| uri                             | 0.12.0       |
| openssl                         | 3.1.0        |
| digest                          | 3.1.1        |
| ipaddr                          | 1.2.5        |
| resolv                          | 0.2.2        |
| time                            | 0.2.1        |
| stringio                        | 3.0.4        |
| open-uri                        | 0.3.0        |
| mutex_m                         | 0.1.2        |
| net-http                        | 0.3.2        |
| net-protocol                    | 0.2.1        |
| ostruct                         | 0.5.5        |
| english                         | 0.7.2        |
| erb                             | 4.0.2        |
| abbrev                          | 0.1.1        |
| tempfile                        | 0.1.3        |
| delegate                        | 0.3.0        |
| fileutils                       | 1.7.0        |
| tmpdir                          | 0.1.3        |
| base64                          | 0.1.1        |
| singleton                       | 0.1.1        |
| open3                           | 0.1.2        |
| nkf                             | 0.1.2        |
| mini_portile2                   | 2.8.1        |
| racc                            | 1.6.2        |
| nokogiri                        | 1.13.10      |
| prettyprint                     | 0.1.1        |
| pp                              | 0.4.0        |
| find                            | 0.1.1        |
| yaml                            | 0.2.1        |
| psych                           | 5.0.1        |
</details>

**Comment by crazymanish** [comment]
slather has new release, there should not be any issue now. closing it https://github.com/SlatherOrg/slather/pull/532#issuecomment-1380710532

**Comment by drosenstark** [comment]
Thanks, this help me cut through a wall of confusion about Ruby 3.2.2. The fastlane docs say it's okay but use 2.7 as an example. Rvm doesn't have a binary at the ready for any 3.x versions. So after seeing this thread, I installed 3.2.2 via brew and it runs perfectly with Fastlane.

Which is not the point of this thread, but... isn't it?

Thanks!
