### ISSUE TITLE
[regression] Match crashes with [!] undefined method `id'

### ISSUE THREAD

**Issue by Sega-Zero** [fastlane/fastlane#17008]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: 2.155.0
- Last working version: 2.154.0

### Regression Description
match crashes while trying to create a keychain. Probably regressed by #16920

##### Complete output when running fastlane, including the stack trace and command used
<details>

```ruby

[12:13:24]: ---------------------
[12:13:24]: --- Step: produce ---
[12:13:24]: ---------------------

+---------------------------+-------------------------------------------------------+
|                            Summary for produce 2.155.0                            |
+---------------------------+-------------------------------------------------------+
| app_identifier            | com.test.app.improve.Share-Extension |
| app_name                  | com.test.app.improve.Share-Extension |
| skip_itc                  | true                                                  |
| enable_services.app_group | on                                                    |
| username                  | ****                                      |
| sku                       | <REDACTED>                                            |
| platform                  | ios                                                   |
| language                  | English                                               |
| skip_devcenter            | false                                                 |
| team_id                   | ****                                            |
| team_name                 | <REDACTED>                            |
| itc_team_id               | <REDACTED>                                              |
+---------------------------+-------------------------------------------------------+

Available session is not valid any more. Continuing with normal login.
[12:13:27]: Creating new app 'com.test.app.improve.Share-Extension' on the Apple Dev Center
[12:13:28]: Your app name includes non-ASCII characters, which are not supported by the Apple Developer Portal.
[12:13:28]: To fix this a unique (internal) name 'comtestappimproveShareExtension 44739fd23f15540f77d17e6d72085012' has been created for you. Your app's real name 'com.test.app.improve.Share-Extension'
[12:13:28]: will still show up correctly on App Store Connect and the App Store.
[12:13:28]: Created app <REDACTED>
[12:13:29]: Finished creating new app 'com.test.app.improve.Share-Extension' on the Dev Center
[12:13:29]: --------------------------------------------------------------------
[12:13:29]: Step: fastlane produce associate_group --app_identifier com.test.app.improve.Share-Extension group.com.test.app.improve --skip_itc true --app_name com.test.app.improve.Share-Extension
[12:13:29]: --------------------------------------------------------------------
[12:13:29]: $ fastlane produce associate_group --app_identifier com.test.app.improve.Share-Extension group.com.test.app.improve --skip_itc true --app_name com.test.app.improve.Share-Extension
[12:13:32]: ▸ [12:13:32]: Starting login with user ****
[12:13:33]: ▸ Available session is not valid any more. Continuing with normal login.
[12:13:34]: ▸ [12:13:34]: Successfully logged in
[12:13:37]: ▸ [12:13:37]: Validating groups before association
[12:13:38]: ▸ [12:13:38]: Finalising association with 1 groups
[12:13:39]: ▸ [12:13:39]: Done!
[12:13:40]: -------------------
[12:13:40]: --- Step: match ---
[12:13:40]: -------------------

+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                                                                                      Summary for match 2.155.0                                                                                       |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| git_branch                     | master                                                                                                                                                              |
| type                           | development                                                                                                                                                         |
| app_identifier                 | ["com.test.app.improve", "com.test.app.improve.PushNotificationService", "com.test.app.improve.Share-Extension"] |
| force_for_new_devices          | true                                                                                                                                                                |
| force                          | false                                                                                                                                                               |
| readonly                       | false                                                                                                                                                               |
| generate_apple_certs           | true                                                                                                                                                                |
| skip_provisioning_profiles     | false                                                                                                                                                               |
| username                       | ****                                                                                                                                                    |
| team_id                        | ****                                                                                                                                                          |
| team_name                      | <REDACTED>                                                                                                                                          |
| storage_mode                   | git                                                                                                                                                                 |
| git_url                        | ****                                                                                        |
| shallow_clone                  | false                                                                                                                                                               |
| clone_branch_directly          | false                                                                                                                                                               |
| keychain_name                  | ios-build.keychain                                                                                                                                                  |
| keychain_password              | ********                                                                                                                                                            |
| skip_confirmation              | false                                                                                                                                                               |
| skip_docs                      | false                                                                                                                                                               |
| platform                       | ios                                                                                                                                                                 |
| derive_catalyst_app_identifier | false                                                                                                                                                               |
| fail_on_name_taken             | false                                                                                                                                                               |
| verbose                        | false                                                                                                                                                               |
+--------------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------+

[12:13:40]: Cloning remote git repo...
[12:13:40]: If cloning the repo takes too long, you can use the `clone_branch_directly` option in match.
[12:14:21]: Checking out branch master...
[12:14:22]: 🔓  Successfully decrypted certificates repo
[12:14:22]: Verifying that the certificate and profile are still valid on the Dev Portal...
Available session is not valid any more. Continuing with normal login.
[12:14:26]: Installing certificate...
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[12:14:27]: There are no local code signing identities found.
You can run `security find-identity -v -p codesigning ios-build.keychain` to get this output.
This Stack Overflow thread has more information: https://stackoverflow.com/q/35390072/774.
(Check in Keychain Access for an expired WWDR certificate: https://stackoverflow.com/a/35409835/774 has more info.)
[12:14:28]: Setting key partition list... (this can take a minute if there are a lot of keys installed)
[12:14:28]: security: SecItemCopyMatching: The specified item could not be found in the keychain.
[12:14:28]: Setting key partition list... (this can take a minute if there are a lot of keys installed)

+-------------------+-------------------------------------------+
|                     Installed Certificate                     |
+-------------------+-------------------------------------------+
| User ID           | <REDACTED>                                |
| Common Name       | Apple Development: <REDACTED> |
| Organisation Unit | ****                                |
| Organisation      | <REDACTED>                |
| Country           | US                                        |
| Start Datetime    | 2020-02-03 09:41:43 UTC                   |
| End Datetime      | 2021-02-02 09:41:43 UTC                   |
+-------------------+-------------------------------------------+


+-------------------------------------+---------------------------------------------------------+
|                                   Summary for sigh 2.155.0                                    |
+-------------------------------------+---------------------------------------------------------+
| app_identifier                      | com.test.app.improve                   |
| username                            | ****                                        |
| force                               | false                                                   |
| cert_id                             | <REDACTED>                                              |
| provisioning_name                   | match Development com.test.app.improve |
| ignore_profiles_with_different_name | true                                                    |
| team_id                             | ****                                              |
| team_name                           | <REDACTED>                              |
| fail_on_name_taken                  | false                                                   |
| platform                            | ios                                                     |
| development                         | true                                                    |
| adhoc                               | false                                                   |
| developer_id                        | false                                                   |
| skip_install                        | false                                                   |
| skip_fetch_profiles                 | false                                                   |
| skip_certificate_verification       | false                                                   |
| readonly                            | false                                                   |
+-------------------------------------+---------------------------------------------------------+

[12:14:29]: Starting login with user ****
Available session is not valid any more. Continuing with normal login.
[12:14:31]: Successfully logged in
[12:14:31]: Fetching profiles...
[12:14:37]: Verifying certificates...
[12:14:37]: No existing profiles found, that match the certificates you have installed locally! Creating a new provisioning profile for you
[12:14:49]: Creating new provisioning profile for 'com.test.app.improve' with name 'match Development com.test.app.improve' for 'ios' platform
security: SecKeychainSearchCopyNext: The specified item could not be found in the keychain.
[12:14:53]: -------------------
[12:14:53]: --- Step: is_ci ---
[12:14:53]: -------------------
[12:14:53]: --------------------------
[12:14:53]: --- Step: fastlane env ---
[12:14:53]: --------------------------
[12:14:58]: ▸ [12:14:57]: Take notice that this output may contain sensitive information, or simply information that you don't want to make public.
[12:14:58]: ▸ [12:14:57]: Open https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅
+------------------------+-----------------------------------------------------------------+
|                                       Lane Context                                       |
+------------------------+-----------------------------------------------------------------+
| DEFAULT_PLATFORM       | ios                                                             |
| PLATFORM_NAME          | ios                                                             |
| LANE_NAME              | ios auto                                                        |
| KEYCHAIN_PATH          | ~/Library/Keychains/ios-build.keychain                          |
| VERSION_NUMBER         | 1.0.0                                                      |
| BUILD_NUMBER           | 1.0.0                                                      |
| APP_GROUP_IDENTIFIERS  | ["group.com.test.app.improve"]                 |
| KEYCHAIN_ACCESS_GROUPS | ["$(AppIdentifierPrefix)com.test.app.improve"] |
| PRODUCE_APPLE_ID       |                                                                 |
+------------------------+-----------------------------------------------------------------+

+------+---------------------------------------------------------------+-------------+
|                                  fastlane summary                                  |
+------+---------------------------------------------------------------+-------------+
| Step | Action                                                        | Time (in s) |
+------+---------------------------------------------------------------+-------------+
| 1    | default_platform                                              | 0           |
| 2    | git_branch                                                    | 0           |
| 3   | produce                                                       | 3           |
| 4   | fastlane produce associate_group --app_identifier com.mango.t | 8           |
| 5   | produce                                                       | 4           |
| 6   | fastlane produce associate_group --app_identifier com.mango.t | 10          |
| 💥   | match                                                         | 72          |
| 8   | is_ci                                                         | 0           |
| 9   | fastlane env                                                  | 5           |
+------+---------------------------------------------------------------+-------------+

[12:14:58]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

➡️  Error when trying to initialize Deliver.
    https://github.com/fastlane/fastlane/issues/16951 [open] 3 💬
    2 days ago

➡️  Having deliver/upload_to_app_store issues? Install 2.150.0.rc5
    https://github.com/fastlane/fastlane/issues/16639 [closed] 116 💬
    4 weeks ago

➡️  undefined method `login' for Spaceship::Tunes:Module
    https://github.com/fastlane/fastlane/issues/15495 [closed] 7 💬
    13 Feb 2020

and 31 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60id%27%20for%20Array&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/sigh/lib/sigh/runner.rb:174:in `create_profile!': [!] undefined method `id' for #<Array:0x00007fed14d924d0> (NoMethodError)
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/sigh/lib/sigh/runner.rb:42:in `run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/sigh/lib/sigh/manager.rb:8:in `start'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/generator.rb:103:in `generate_provisioning_profile'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/runner.rb:262:in `fetch_provisioning_profile'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/runner.rb:109:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/runner.rb:108:in `loop'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/runner.rb:108:in `block in run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/runner.rb:107:in `each'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/match/lib/match/runner.rb:107:in `run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/actions/sync_code_signing.rb:13:in `run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:259:in `block (2 levels) in parsing_binding'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:356:in `block (2 levels) in parsing_binding'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:204:in `try_switch_to_lane'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:146:in `trigger_action_by_name'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:425:in `block (2 levels) in parsing_binding'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/commands_generator.rb:352:in `run'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Users/user/.rvm/gems/ruby-2.4.5/gems/fastlane-2.155.0/bin/fastlane:23:in `<top (required)>'
	from /Users/user/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `load'
	from /Users/user/.rvm/gems/ruby-2.4.5/bin/fastlane:23:in `<main>'
	from /Users/user/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `eval'
	from /Users/user/.rvm/gems/ruby-2.4.5/bin/ruby_executable_hooks:24:in `<main>'
script returned exit code 1
```
</details>

### Environment

<details>
  <pre>
[12:14:53]: $ fastlane env
[12:14:56]: ▸ [12:14:56]: Generating fastlane environment output, this might take a few seconds...
[12:14:57]: ▸ <details><summary>✅ fastlane environment ✅</summary>
[12:14:57]: ▸ ### Stack
[12:14:57]: ▸ | Key                         | Value                                       |
[12:14:57]: ▸ | --------------------------- | ------------------------------------------- |
[12:14:57]: ▸ | OS                          | 10.14.4                                     |
[12:14:57]: ▸ | Ruby                        | 2.4.5                                       |
[12:14:57]: ▸ | Bundler?                    | true                                        |
[12:14:57]: ▸ | Git                         | git version 2.21.1 (Apple Git-122.3)        |
[12:14:57]: ▸ | Installation Source         | ~/.rvm/gems/ruby-2.4.5/bin/fastlane         |
[12:14:57]: ▸ | Host                        | Mac OS X 10.14.4 (18E2034)                  |
[12:14:57]: ▸ | Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.5/lib                |
[12:14:57]: ▸ | OpenSSL Version             | OpenSSL 1.1.1d  10 Sep 2019                 |
[12:14:57]: ▸ | Is contained                | false                                       |
[12:14:57]: ▸ | Is homebrew                 | false                                       |
[12:14:57]: ▸ | Is installed via Fabric.app | false                                       |
[12:14:57]: ▸ | Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
[12:14:57]: ▸ | Xcode Version               | 11.3.1                                      |
[12:14:57]: ▸ ### System Locale
[12:14:57]: ▸ | Variable | Value       |   |
[12:14:57]: ▸ | -------- | ----------- | - |
[12:14:57]: ▸ | LANG     | ru_RU.UTF-8 | ✅ |
[12:14:57]: ▸ | LC_ALL   |             |   |
[12:14:57]: ▸ | LANGUAGE |             |   |
[12:14:58]: ▸ ### fastlane gems
[12:14:58]: ▸ | Gem      | Version | Update-Status |
[12:14:58]: ▸ | -------- | ------- | ------------- |
[12:14:58]: ▸ | fastlane | 2.155.0 | ✅ Up-To-Date  |
[12:14:58]: ▸ ### Loaded fastlane plugins:
[12:14:58]: ▸ | Plugin                                    | Version | Update-Status |
[12:14:58]: ▸ | ----------------------------------------- | ------- | ------------- |
[12:14:58]: ▸ | fastlane-plugin-firebase_management       | 1.1.0   | ✅ Up-To-Date  |
[12:14:58]: ▸ | fastlane-plugin-firebase_app_distribution | 0.1.4   | ✅ Up-To-Date  |
[12:14:58]: ▸ <details><summary><b>Loaded gems</b></summary>
[12:14:58]: ▸ | Gem                                       | Version      |
[12:14:58]: ▸ | ----------------------------------------- | ------------ |
[12:14:58]: ▸ | did_you_mean                              | 1.1.0        |
[12:14:58]: ▸ | bundler                                   | 1.17.3       |
[12:14:58]: ▸ | rake                                      | 13.0.1       |
[12:14:58]: ▸ | CFPropertyList                            | 3.0.2        |
[12:14:58]: ▸ | concurrent-ruby                           | 1.1.6        |
[12:14:58]: ▸ | i18n                                      | 0.9.5        |
[12:14:58]: ▸ | minitest                                  | 5.14.1       |
[12:14:58]: ▸ | thread_safe                               | 0.3.6        |
[12:14:58]: ▸ | tzinfo                                    | 1.2.7        |
[12:14:58]: ▸ | activesupport                             | 4.2.11.3     |
[12:14:58]: ▸ | public_suffix                             | 4.0.5        |
[12:14:58]: ▸ | addressable                               | 2.7.0        |
[12:14:58]: ▸ | httpclient                                | 2.8.3        |
[12:14:58]: ▸ | json                                      | 2.3.1        |
[12:14:58]: ▸ | algoliasearch                             | 1.27.3       |
[12:14:58]: ▸ | atomos                                    | 0.1.3        |
[12:14:58]: ▸ | aws-eventstream                           | 1.1.0        |
[12:14:58]: ▸ | aws-partitions                            | 1.351.0      |
[12:14:58]: ▸ | aws-sigv4                                 | 1.2.1        |
[12:14:58]: ▸ | jmespath                                  | 1.4.0        |
[12:14:58]: ▸ | aws-sdk-core                              | 3.104.3      |
[12:14:58]: ▸ | aws-sdk-kms                               | 1.36.0       |
[12:14:58]: ▸ | aws-sdk-s3                                | 1.75.0       |
[12:14:58]: ▸ | babosa                                    | 1.0.3        |
[12:14:58]: ▸ | claide                                    | 1.0.3        |
[12:14:58]: ▸ | fuzzy_match                               | 2.0.4        |
[12:14:58]: ▸ | nap                                       | 1.1.0        |
[12:14:58]: ▸ | netrc                                     | 0.11.0       |
[12:14:58]: ▸ | ffi                                       | 1.13.1       |
[12:14:58]: ▸ | ethon                                     | 0.12.0       |
[12:14:58]: ▸ | typhoeus                                  | 1.4.0        |
[12:14:58]: ▸ | cocoapods-core                            | 1.9.3        |
[12:14:58]: ▸ | cocoapods-deintegrate                     | 1.0.4        |
[12:14:58]: ▸ | cocoapods-downloader                      | 1.4.0        |
[12:14:58]: ▸ | cocoapods-plugins                         | 1.0.0        |
[12:14:58]: ▸ | cocoapods-search                          | 1.0.0        |
[12:14:58]: ▸ | cocoapods-stats                           | 1.1.0        |
[12:14:58]: ▸ | cocoapods-trunk                           | 1.5.0        |
[12:14:58]: ▸ | cocoapods-try                             | 1.2.0        |
[12:14:58]: ▸ | colored2                                  | 3.1.2        |
[12:14:58]: ▸ | escape                                    | 0.0.4        |
[12:14:58]: ▸ | fourflusher                               | 2.3.1        |
[12:14:58]: ▸ | gh_inspector                              | 1.1.3        |
[12:14:58]: ▸ | molinillo                                 | 0.6.6        |
[12:14:58]: ▸ | ruby-macho                                | 1.4.0        |
[12:14:58]: ▸ | nanaimo                                   | 0.3.0        |
[12:14:58]: ▸ | xcodeproj                                 | 1.17.1       |
[12:14:58]: ▸ | cocoapods                                 | 1.9.3        |
[12:14:58]: ▸ | colored                                   | 1.2          |
[12:14:58]: ▸ | highline                                  | 1.7.10       |
[12:14:58]: ▸ | commander-fastlane                        | 4.4.6        |
[12:14:58]: ▸ | declarative                               | 0.0.20       |
[12:14:58]: ▸ | declarative-option                        | 0.1.0        |
[12:14:58]: ▸ | digest-crc                                | 0.6.1        |
[12:14:58]: ▸ | unf_ext                                   | 0.0.7.7      |
[12:14:58]: ▸ | unf                                       | 0.1.4        |
[12:14:58]: ▸ | domain_name                               | 0.5.20190701 |
[12:14:58]: ▸ | dotenv                                    | 2.7.6        |
[12:14:58]: ▸ | emoji_regex                               | 3.0.0        |
[12:14:58]: ▸ | excon                                     | 0.76.0       |
[12:14:58]: ▸ | multipart-post                            | 2.0.0        |
[12:14:58]: ▸ | faraday                                   | 1.0.1        |
[12:14:58]: ▸ | http-cookie                               | 1.0.3        |
[12:14:58]: ▸ | faraday-cookie_jar                        | 0.0.6        |
[12:14:58]: ▸ | faraday_middleware                        | 1.0.0        |
[12:14:58]: ▸ | fastimage                                 | 2.2.0        |
[12:14:58]: ▸ | jwt                                       | 2.2.1        |
[12:14:58]: ▸ | memoist                                   | 0.16.2       |
[12:14:58]: ▸ | multi_json                                | 1.15.0       |
[12:14:58]: ▸ | os                                        | 1.1.1        |
[12:14:58]: ▸ | signet                                    | 0.14.0       |
[12:14:58]: ▸ | googleauth                                | 0.13.1       |
[12:14:58]: ▸ | mini_mime                                 | 1.0.2        |
[12:14:58]: ▸ | uber                                      | 0.1.0        |
[12:14:58]: ▸ | representable                             | 3.0.4        |
[12:14:58]: ▸ | retriable                                 | 3.1.2        |
[12:14:58]: ▸ | google-api-client                         | 0.38.0       |
[12:14:58]: ▸ | google-cloud-env                          | 1.3.3        |
[12:14:58]: ▸ | google-cloud-errors                       | 1.0.1        |
[12:14:58]: ▸ | google-cloud-core                         | 1.5.0        |
[12:14:58]: ▸ | google-cloud-storage                      | 1.27.0       |
[12:14:58]: ▸ | mini_magick                               | 4.10.1       |
[12:14:58]: ▸ | plist                                     | 3.5.0        |
[12:14:58]: ▸ | rubyzip                                   | 2.3.0        |
[12:14:58]: ▸ | security                                  | 0.1.3        |
[12:14:58]: ▸ | naturally                                 | 2.2.0        |
[12:14:58]: ▸ | simctl                                    | 1.6.8        |
[12:14:58]: ▸ | slack-notifier                            | 2.3.2        |
[12:14:58]: ▸ | terminal-notifier                         | 2.0.0        |
[12:14:58]: ▸ | unicode-display_width                     | 1.7.0        |
[12:14:58]: ▸ | terminal-table                            | 1.8.0        |
[12:14:58]: ▸ | tty-screen                                | 0.8.1        |
[12:14:58]: ▸ | tty-cursor                                | 0.7.1        |
[12:14:58]: ▸ | tty-spinner                               | 0.9.3        |
[12:14:58]: ▸ | word_wrap                                 | 1.0.0        |
[12:14:58]: ▸ | rouge                                     | 2.0.7        |
[12:14:58]: ▸ | xcpretty                                  | 0.3.0        |
[12:14:58]: ▸ | xcpretty-travis-formatter                 | 1.0.0        |
[12:14:58]: ▸ | fastlane-plugin-firebase_app_distribution | 0.1.4        |
[12:14:58]: ▸ | mime-types-data                           | 3.2020.0512  |
[12:14:58]: ▸ | mime-types                                | 3.3.1        |
[12:14:58]: ▸ | multi_xml                                 | 0.6.0        |
[12:14:58]: ▸ | httparty                                  | 0.18.1       |
[12:14:58]: ▸ | fastlane-plugin-firebase_management       | 1.1.0        |
[12:14:58]: ▸ | mustache                                  | 1.1.1        |
[12:14:58]: ▸ | open4                                     | 1.3.4        |
[12:14:58]: ▸ | redcarpet                                 | 3.5.0        |
[12:14:58]: ▸ | sassc                                     | 2.4.0        |
[12:14:58]: ▸ | sqlite3                                   | 1.4.2        |
[12:14:58]: ▸ | liferaft                                  | 0.0.6        |
[12:14:58]: ▸ | xcinvoke                                  | 0.3.0        |
[12:14:58]: ▸ | jazzy                                     | 0.13.5       |
[12:14:58]: ▸ </details>
[12:14:58]: ▸ *generated on:* **2020-08-06**
[12:14:58]: ▸ </details></pre>
</details>

**Comment by joshdholtz** [comment]
@Sega-Zero On it!

**Comment by joshdholtz** [comment]
@Sega-Zero Found the error! Writing tests for this and then will get a new version made 💪

**Comment by joshdholtz** [comment]
@Sega-Zero Fix is here ☝️ Will start release process once tests pass
