### ISSUE TITLE
- hockey() command error on fastlane 2.42.0

### ISSUE THREAD

**Issue by DavidArayan** [fastlane/fastlane#9614]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

The hockey() command on the latest fastlane 2.42.0 produces the following error. Using the exact same input on 2.41.0 is actually fine. We use CircleCI with XCode 8.3, also tested using XCode 8.2 with no difference.

We also tried purging our CircleCI caches to make sure nothing weird was getting in the way.

hockey(
        api_token: 'our token',
        owner_id: 'our owner',
        notes: 'changelog',
        create_update: false,
        strategy: 'replace'
 )

It's also interesting that the build actually gets uploaded into hockey-app when this error occurs which leads me to believe there is some kind of error during the response from hockey-app.

For now, we have rolled back to 2.41.0 to work around this problem.

Specific error is: TypeError: [!] no implicit conversion of nil into String

##### Complete output when running fastlane, including the stack trace and command used
> You can use: `--capture_output` as the last commandline argument to get that collected for you

[INSERT OUTPUT HERE]

TypeError: [!] no implicit conversion of nil into String
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/actions/hockey.rb:174:in `+'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/actions/hockey.rb:174:in `run'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:226:in `chdir'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
  Fastfile:207:in `block (2 levels) in parsing_binding'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:39:in `run!'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/gems/fastlane-2.42.0/bin/fastlane:20:in `<top (required)>'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `load'
  /Users/distiller/app-ios/vendor/bundle/ruby/2.3.0/bin/fastlane:22:in `<top (required)>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[INSERT OUTPUT HERE]

We use Circle CI with XCode 8.3. Error only occurs when using fastlane 2.42.0. Command to run was bundle exec fastlane via circle.yml

**Comment by amitjpatel** [comment]
Getting the same issue, believe it's related to this commit:
https://github.com/fastlane/fastlane/commit/ed4108af99748c472e97edab83d794a9b2ff87b7
@wolffan Is it possible to update your pull request?

**Comment by wolffan** [comment]
@amitjpatel yes, must be. It's merged but I can make a new one

**Comment by wolffan** [comment]
I need to see what is the answer on hockey when you use 'strategy':'replace' :/. 
But on the API docs there's no reference that the actual payload changes

**Comment by DavidArayan** [comment]
@wolffan if it helps i've also tried with this command and it gets the same error. This is the simplest command that we use.

hockey(
api_token: 'our token',
owner_id: 'our owner',
notes: 'changelog'
)

I can confirm that none of those values would be nil.

**Comment by amitjpatel** [comment]
@wolffan I don't think it matters which 'strategy' you use. 
There is no parameter 'version'; hence why the concatenation fails :(

**Comment by wolffan** [comment]
Seems I used the wrong version of the docs for the PR. I looked at [this](https://support.hockeyapp.net/kb/api/api-versions#upload-version)

**Comment by GoodMirek** [comment]
We are affected too by this issue. We do just plain upload of IPA and symbols ZIP files.

**Comment by Sega-Zero** [comment]
Same here

**Comment by wolffan** [comment]
working on that, sorry for this headache :(

**Comment by lexusilia** [comment]
We are affected too by this issue. As we see we have crash in hockey.rb:174
After hockey.rb handled response after successful code snapshot (hockey.rb):
```
when 200...300
  url = response.body['public_url']
  version_url = url + "/app_versions/" + response.body['version']
  Actions.lane_context[SharedValues::HOCKEY_DOWNLOAD_LINK] = version_url
  Actions.lane_context[SharedValues::HOCKEY_BUILD_INFORMATION] = response.body

  UI.message("Version Download URL: #{version_url}") if version_url
  UI.message("Public Download URL: #{url}") if url
  UI.success('Build successfully uploaded to HockeyApp!')
else
```
Crash occurred in  `version_url = url + "/app_versions/" + response.body['version']` line.

**Comment by romk1n** [comment]
same issue here :(

**Comment by wolffan** [comment]
This should be fixed with the new 2.43.0 version

**Comment by tomekjarosik** [comment]
I still see an error: /Library/Ruby/Gems/2.0.0/gems/fastlane-2.43.0/fastlane/lib/fastlane/actions/hockey.rb:191:in `download_url': [31m[!] undefined method `+' for nil:NilClass[0m (NoMethodError)
Any hints?

**Comment by KrauseFx** [comment]
Could you all try https://github.com/fastlane/fastlane/releases/tag/2.44.0?

**Comment by tomekjarosik** [comment]
Same error with 2.44.0

**Comment by Sega-Zero** [comment]
works in Travis-CI in 2.43.0
