### ISSUE TITLE
undefined method `each' for nil:NilClass

### ISSUE THREAD

**Issue by JsonKit** [fastlane/fastlane#15621]
### New Issue Checklist

- [ ] Updated fastlane to the latest version
- [ ] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [ ] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

### Environment

<details>
  <pre> [REPLACE THIS WITH YOUR INFORMATION] </pre>
</details>

**Comment by ggirotto** [comment]
Have you solved this issue? If yes, how?

**Comment by jjochen** [comment]
same here

**Comment by andyshephard** [comment]
I experienced this error when I updated from fastlane v2.137.0 to v2.140.0
Gemfile.lock shows the following:
> Using CFPropertyList 3.0.2 (was 2.3.6)
Using public_suffix 2.0.5
Using addressable 2.7.0
Using atomos 0.1.3
Using babosa 1.0.3
Using bundler 1.17.2
Using claide 1.0.3
Using colored 1.2
Using colored2 3.1.2
Using highline 1.7.10
Using commander-fastlane 4.4.6
Using declarative 0.0.10
Using declarative-option 0.1.0
Using digest-crc 0.4.1
Using unf_ext 0.0.7.6
Using unf 0.1.4
Using domain_name 0.5.20190701
Using dotenv 2.7.5
Using emoji_regex 1.0.1
Using excon 0.71.1 (was 0.70.0)
Using multipart-post 2.0.0
Using faraday 0.17.3 (was 0.17.1)
Using http-cookie 1.0.3
Using faraday-cookie_jar 0.0.6
Using faraday_middleware 0.13.1
Using fastimage 2.1.7
Using gh_inspector 1.1.3
Using jwt 2.1.0
Using memoist 0.16.2
Using multi_json 1.14.1
Using os 1.0.1
Using signet 0.12.0
Using googleauth 0.10.0 (was 0.6.7)
Using httpclient 2.8.3
Using mini_mime 1.0.2
Using uber 0.1.0
Using representable 3.0.4
Using retriable 3.1.2
Using google-api-client 0.36.4 (was 0.23.9)
Using google-cloud-env 1.3.0
Using google-cloud-core 1.4.1
Using google-cloud-storage 1.25.1 (was 1.16.0)
Using json 2.3.0 (was 2.1.0)
Using mini_magick 4.10.1 (was 4.9.5)
Using multi_xml 0.6.0
Using plist 3.5.0
Using rubyzip 1.3.0
Using security 0.1.3
Using naturally 2.2.0
Using simctl 1.6.7 (was 1.6.6)
Using slack-notifier 2.3.2
Using terminal-notifier 2.0.0
Using unicode-display_width 1.6.0
Using terminal-table 1.8.0
Using tty-screen 0.7.0
Using tty-cursor 0.7.0
Using tty-spinner 0.9.2 (was 0.9.1)
Using word_wrap 1.0.0
Using nanaimo 0.2.6
Using xcodeproj 1.14.0 (was 1.13.0)
Using rouge 2.0.7
Using xcpretty 0.3.0
Using xcpretty-travis-formatter 1.0.0
Fetching fastlane 2.140.0 (was 2.137.0)
Installing fastlane 2.140.0 (was 2.137.0)
Using fastlane-plugin-notarize 1.1.0

Reverting back to the previous Gemfile.lock works for me.

**Comment by jaroslavas** [comment]
Had the same on fresh Catalina machine. Was able to fix it by downgrading fastlane:
```
sudo gem uninstall fastlane
sudo gem install fastlane --version '<= 2.138'
```
Starting from v2.139 I get 
```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.139.0/scan/lib/scan/runner.rb:35:in 'test_app': [!] undefined method `each' for nil:NilClass (NoMethodError)
```

Looks like changes in [this PR](https://github.com/fastlane/fastlane/pull/15749/files#diff-b6a3ba6dff446741cb76248e99156be7) are causing the issue. Probably devices array should be check for lin before using.

**Comment by jjochen** [comment]
The crash is related to the configuration `disable_slide_to_type` which is enabled by default. Disabling it solved the issue for me.
```
    run_tests(
      ...
      disable_slide_to_type: false
    )
```

**Comment by jaroslavas** [comment]
Yes, when you disable it, the code that crashes does not execute. But it's a useful feature, so it would be good to fix it.
