### ISSUE TITLE
Fastlane getting "The request could not be completed because: Server error got 500" error for iOS Apps

### ISSUE THREAD

**Issue by ignite-daniel** [fastlane/fastlane#21199]
Fastlane failing with the error message **_The request could not be completed because: Server error got 500_** but verbose shows it fails when uploading IPA file to App Store Connect.

Please what could be the issue and how do I go about solving this ?

I have been experiencing this for 3 days now.

**Comment by ignite-daniel** [comment]
<img width="877" alt="image" src="https://user-images.githubusercontent.com/89994066/232256377-2a3d6d2d-3742-4db4-991c-125966549e60.png">

**Comment by demonguru18** [comment]
Yeah I can confirm, this is happening on apps - After Screenshot upload the process fails with 500 error . No detailed error thrown

**Comment by pranav-g10** [comment]
Facing the same issue for the past 3 days. Below is the output for `fastlane env`

<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 13.0.1                                      |
| Ruby                        | 2.7.2                                       |
| Bundler?                    | true                                        |
| Git                         | git version 2.37.1 (Apple Git-137.1)        |
| Installation Source         | ~/.rvm/gems/ruby-2.7.2/bin/fastlane         |
| Host                        | macOS 13.0.1 (22A400)                       |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.7.2/lib                |
| OpenSSL Version             | OpenSSL 1.1.1s  1 Nov 2022                  |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 14.1                                        |
| Swift Version               | 5.7.1                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US       | 🚫 |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |


### fastlane gems

| Gem      | Version | Update-Status      |
| -------- | ------- | ------------------ |
| fastlane | 2.212.1 | 🚫 Update available |


### Loaded fastlane plugins:

| Plugin                 | Version | Update-Status |
| ---------------------- | ------- | ------------- |
| fastlane-plugin-aws_s3 | 2.1.0   | ✅ Up-To-Date  |
| fastlane-plugin-sentry | 1.15.0  | ✅ Up-To-Date  |


<details><summary><b>Loaded gems</b></summary>

| Gem                             | Version       |
| ------------------------------- | ------------- |
| did_you_mean                    | 1.4.0         |
| rake                            | 13.0.6        |
| rexml                           | 3.2.5         |
| CFPropertyList                  | 3.0.6         |
| concurrent-ruby                 | 1.2.0         |
| i18n                            | 1.12.0        |
| minitest                        | 5.17.0        |
| tzinfo                          | 2.0.6         |
| activesupport                   | 7.0.4.2       |
| public_suffix                   | 5.0.1         |
| addressable                     | 2.8.1         |
| rubyzip                         | 2.3.2         |
| apktools                        | 0.7.4         |
| artifactory                     | 3.0.15        |
| atomos                          | 0.1.3         |
| aws-eventstream                 | 1.2.0         |
| aws-partitions                  | 1.718.0       |
| aws-sigv4                       | 1.5.2         |
| jmespath                        | 1.6.2         |
| aws-sdk-core                    | 3.170.0       |
| aws-sdk-kms                     | 1.63.0        |
| aws-sdk-s3                      | 1.119.1       |
| babosa                          | 1.0.4         |
| bundler                         | 2.1.4         |
| claide                          | 1.1.0         |
| coderay                         | 1.1.3         |
| colored                         | 1.2           |
| colored2                        | 3.1.2         |
| highline                        | 2.0.3         |
| commander                       | 4.6.0         |
| declarative                     | 0.0.20        |
| digest-crc                      | 0.6.4         |
| unf_ext                         | 0.0.8.2       |
| unf                             | 0.1.4         |
| domain_name                     | 0.5.20190701  |
| dotenv                          | 2.8.1         |
| emoji_regex                     | 3.2.3         |
| excon                           | 0.99.0        |
| faraday-em_http                 | 1.0.0         |
| faraday-em_synchrony            | 1.0.0         |
| faraday-excon                   | 1.1.0         |
| faraday-httpclient              | 1.0.1         |
| multipart-post                  | 2.0.0         |
| faraday-multipart               | 1.0.4         |
| faraday-net_http                | 1.0.1         |
| faraday-net_http_persistent     | 1.2.0         |
| faraday-patron                  | 1.0.0         |
| faraday-rack                    | 1.0.0         |
| faraday-retry                   | 1.0.3         |
| ruby2_keywords                  | 0.0.5         |
| faraday                         | 1.10.3        |
| http-cookie                     | 1.0.5         |
| faraday-cookie_jar              | 0.0.7         |
| faraday_middleware              | 1.2.0         |
| fastimage                       | 2.2.6         |
| gh_inspector                    | 1.1.3         |
| jwt                             | 2.7.0         |
| memoist                         | 0.16.2        |
| multi_json                      | 1.15.0        |
| os                              | 1.1.4         |
| signet                          | 0.17.0        |
| googleauth                      | 1.3.0         |
| httpclient                      | 2.8.3         |
| mini_mime                       | 1.1.2         |
| trailblazer-option              | 0.1.2         |
| uber                            | 0.1.0         |
| representable                   | 3.2.0         |
| retriable                       | 3.1.2         |
| webrick                         | 1.8.1         |
| google-apis-core                | 0.11.0        |
| google-apis-androidpublisher_v3 | 0.34.0        |
| google-apis-playcustomapp_v1    | 0.13.0        |
| google-apis-iamcredentials_v1   | 0.17.0        |
| google-apis-storage_v1          | 0.19.0        |
| google-cloud-env                | 1.6.0         |
| google-cloud-errors             | 1.3.1         |
| google-cloud-core               | 1.6.0         |
| google-cloud-storage            | 1.44.0        |
| json                            | 2.6.3         |
| mini_magick                     | 4.12.0        |
| naturally                       | 2.2.1         |
| optparse                        | 0.1.1         |
| plist                           | 3.7.0         |
| security                        | 0.1.3         |
| simctl                          | 1.6.10        |
| terminal-notifier               | 2.0.0         |
| unicode-display_width           | 1.8.0         |
| terminal-table                  | 1.8.0         |
| tty-screen                      | 0.8.1         |
| tty-cursor                      | 0.7.1         |
| tty-spinner                     | 0.9.3         |
| word_wrap                       | 1.0.0         |
| nanaimo                         | 0.3.0         |
| xcodeproj                       | 1.22.0        |
| rouge                           | 2.0.7         |
| xcpretty                        | 0.3.0         |
| xcpretty-travis-formatter       | 1.0.1         |
| mime-types-data                 | 3.2023.0218.1 |
| mime-types                      | 3.4.1         |
| fastlane-plugin-aws_s3          | 2.1.0         |
| fastlane-plugin-sentry          | 1.15.0        |
| google-protobuf                 | 3.22.0        |
| googleapis-common-protos-types  | 1.5.0         |
| grpc                            | 1.52.0        |
| googleapis-common-protos        | 1.4.0         |
| gapic-common                    | 0.17.1        |
| gems                            | 1.2.0         |
| google-apis-discovery_v1        | 0.14.0        |
| thor                            | 1.2.1         |
| google-apis-generator           | 0.12.0        |
| google-api-client               | 0.53.0        |
| google-cloud-location           | 0.4.0         |
| google-cloud-firestore-v1       | 0.10.0        |
| rbtree                          | 0.4.6         |
| google-cloud-firestore          | 2.7.2         |
| method_source                   | 1.0.0         |
| pry                             | 0.14.1        |
</details>


*generated on:* **2023-04-17**
</details>

And the output of the upload lane:

<details><summary>🚫 fastlane output 🚫</summary>

```bash
[✔] 🚀 
+------------------------+---------+----------------------------------------------------+
|                                     Used plugins                                      |
+------------------------+---------+----------------------------------------------------+
| Plugin                 | Version | Action                                             |
+------------------------+---------+----------------------------------------------------+
| fastlane-plugin-aws_s3 | 2.1.0   | aws_s3                                             |
| fastlane-plugin-sentry | 1.15.0  | sentry_upload_dsym, sentry_set_commits,            |
|                        |         | sentry_upload_sourcemap, sentry_finalize_release,  |
|                        |         | sentry_upload_file, sentry_create_deploy,          |
|                        |         | sentry_upload_proguard, sentry_create_release,     |
|                        |         | sentry_check_cli_installed, sentry_upload_dif      |
+------------------------+---------+----------------------------------------------------+

[12:24:11]: ---------------------------
[12:24:11]: --- Step: opt_out_usage ---
[12:24:11]: ---------------------------
[12:24:11]: Disabled upload of used actions
[12:24:11]: ------------------------------
[12:24:11]: --- Step: default_platform ---
[12:24:11]: ------------------------------
[12:24:11]: Driving the lane 'ios fitall' 🚀
[12:24:11]: -------------------------------------
[12:24:11]: --- Step: ensure_git_status_clean ---
[12:24:11]: -------------------------------------
[12:24:11]: $ git status --porcelain
[12:24:11]: Git status is clean, all good! 💪
Trainer CID:                            adamsbodyshape
App Identifier:                         com.adamsbodyshape.app
[12:24:13]: ---------------------------------------
[12:24:13]: --- Step: app_store_connect_api_key ---
[12:24:13]: ---------------------------------------
[12:24:13]: ----------------------------------------------
[12:24:13]: --- adamsbodyshape (2.5/2500) ::  w/  META ---
[12:24:13]: ----------------------------------------------
rm -rf /Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape
Downloaded 16 screenshots
[12:24:17]: ---------------------------------
[12:24:17]: --- Step: upload_to_app_store ---
[12:24:17]: ---------------------------------
[12:24:17]: Creating authorization token for App Store Connect API

+--------------------------------------------------------------------+----------------------------------------------------------------------------------------+
|                                                                   deliver 2.212.1 Summary                                                                   |
+--------------------------------------------------------------------+----------------------------------------------------------------------------------------+
| api_key                                                            | ********                                                                               |
| app_identifier                                                     | com.**************.app                                                                 |
| itc_provider                                                       | KHXJN62B4X                                                                             |
| team_id                                                            | KHXJN62B4X                                                                             |
| app_version                                                        | 2.5                                                                                    |
| skip_screenshots                                                   | false                                                                                  |
| skip_metadata                                                      | false                                                                                  |
| reject_if_possible                                                 | true                                                                                   |
| precheck_include_in_app_purchases                                  | false                                                                                  |
| submission_information.content_rights_has_rights                   | true                                                                                   |
| submission_information.content_rights_contains_third_party_content | false                                                                                  |
| submission_information.add_id_info_uses_idfa                       | false                                                                                  |
| submission_information.export_compliance_uses_encryption           | false                                                                                  |
| overwrite_screenshots                                              | true                                                                                   |
| screenshots_path                                                   | /Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape               |
| force                                                              | true                                                                                   |
| run_precheck_before_submit                                         | true                                                                                   |
| skip_binary_upload                                                 | true                                                                                   |
| skip_app_version_update                                            | true                                                                                   |
| release_notes.default                                              | Bug fixes and performance improvements                                                 |
| app_rating_config_path                                             | fastlane/app_rating_config.json                                                        |
| languages                                                          | ["en-US"]                                                                              |
| subtitle.en-US                                                     | Health & Fitness                                                                       |
| submit_for_review                                                  | true                                                                                   |
| automatic_release                                                  | true                                                                                   |
| metadata_path                                                      | ./fastlane/metadata                                                                    |
| platform                                                           | ios                                                                                    |
| edit_live                                                          | false                                                                                  |
| use_live_version                                                   | false                                                                                  |
| sync_screenshots                                                   | false                                                                                  |
| verify_only                                                        | false                                                                                  |
| phased_release                                                     | false                                                                                  |
| reset_ratings                                                      | false                                                                                  |
| precheck_default_rule_level                                        | warn                                                                                   |
| ignore_language_directory_validation                               | false                                                                                  |
+--------------------------------------------------------------------+----------------------------------------------------------------------------------------+

[12:24:20]: Detected languages: ["en-US", "default"]
[12:24:30]: Will begin uploading metadata for '2.5' on App Store Connect
[12:24:30]: Skipping 'release_notes'... this is the first version of the app
[12:24:30]: Uploading metadata to App Store Connect for version
[12:24:34]: Uploading metadata to App Store Connect for localized version 'en-US'
[12:24:36]: Uploading metadata to App Store Connect for localized info 'en-US'
[12:24:43]: Uploading app review information to App Store Connect
[12:24:46]: Setting the app's age rating...
[12:24:51]: Will begin uploading snapshots for '2.5' on App Store Connect
[12:24:51]: Starting with the upload of screenshots...
[12:24:54]: Deleted 'en-US APP_IPHONE_55' -  (1.129229 secs)
[12:24:55]: Deleted 'en-US APP_IPHONE_65' -  (1.438074 secs)
[12:24:55]: Number of screenshots not deleted: 0
[12:24:55]: Successfully deleted all screenshots
[12:25:04]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-07-call.jpg'... (5.522299 secs)
[12:25:04]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-06-activity.jpg'... (5.539879 secs)
[12:25:04]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-05-meal.jpg'... (5.596795 secs)
[12:25:04]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-10-food.jpg'... (5.726122 secs)
[12:25:05]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-01-splash.jpg'... (6.018616 secs)
[12:25:06]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-03-workout.jpg'... (7.291682 secs)
[12:25:06]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-08-about.jpg'... (7.295128 secs)
[12:25:06]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-02-schedule.jpg'... (7.350446 secs)
[12:25:07]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/5-01-splash.jpg'... (8.076089 secs)
[12:25:07]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-02-schedule.jpg'... (8.256965 secs)
[12:25:10]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-03-workout.jpg'... (5.296157 secs)
[12:25:10]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-05-meal.jpg'... (5.358932 secs)
[12:25:11]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-08-about.jpg'... (5.766471 secs)
[12:25:11]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-07-call.jpg'... (6.436146 secs)
[12:25:11]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-06-activity.jpg'... (7.040601 secs)
[12:25:12]: Uploaded '/Users/pranav/Development/fitbud/ios/fastlane/screenshots/adamsbodyshape/en-US/6-10-food.jpg'... (5.995741 secs)
[✔] Waiting for all the screenshots to finish being processed... 
[12:25:21]: Successfully uploaded all screenshots
[✔] Sorting screenshots uploaded... 
[12:25:25]: Successfully uploaded screenshots to App Store Connect
[12:25:25]: Running precheck before submitting to review, if you'd like to disable this check you can set run_precheck_before_submit to false
[12:25:25]: Making sure we pass precheck 👮‍♀️ 👮 before we submit  🛫

+--------------------------+------------------------+
|           Summary for precheck 2.212.1            |
+--------------------------+------------------------+
| default_rule_level       | warn                   |
| include_in_app_purchases | false                  |
| app_identifier           | com.adamsbodyshape.app |
| api_key                  | ********               |
| platform                 | ios                    |
| use_live                 | false                  |
+--------------------------+------------------------+

[12:25:25]: Creating authorization token for App Store Connect API
[12:25:25]: Checking app for precheck rule violations
[12:25:35]: ✅  Passed: No negative  sentiment
[12:25:35]: ✅  Passed: No placeholder text
[12:25:35]: ✅  Passed: No mentioning  competitors
[12:25:35]: ✅  Passed: No future functionality promises
[12:25:35]: ✅  Passed: No words indicating test content
[12:25:35]: ✅  Passed: No curse words
[12:25:35]: ✅  Passed: No words indicating your IAP is free
[12:25:35]: ✅  Passed: Incorrect, or missing copyright date
[12:25:42]: ✅  Passed: No broken urls
[12:25:42]: precheck 👮‍♀️ 👮  finished without detecting any potential problems 🛫
[12:25:43]: Selecting the latest build...
[12:25:43]: Waiting for processing on... app_id: 6447753529, app_version: 2.5, build_version: , platform: IOS
[12:25:45]: Successfully finished processing the build 2.5 - 2500 for IOS
[12:25:45]: Selecting build 2.5 (2500)...
[12:25:49]: Successfully selected build
[12:25:51]: Successfully updated IDFA declarations on App Store Connect
[12:25:52]: Successfully updated contents rights declaration on App Store Connect
[12:26:04]: FITALL FAILED FOR adamsbodyshape with Server error got 500
[12:26:04]: ----------------------------
[12:26:04]: --- Step: reset_git_repo ---
[12:26:04]: ----------------------------
[12:26:04]: $ git reset --hard HEAD
[12:26:04]: ▸ HEAD is now at 3644021a1 Fastlane: prepall updated to use the changes made to fitprep
[12:26:04]: Git repo was reset and cleaned back to a pristine state.
[12:26:04]: Done
[12:26:04]: FITALL FAILED FOR adamsbodyshape with Server error got 500

+------+---------------------------+-------------+
|                fastlane summary                |
+------+---------------------------+-------------+
| Step | Action                    | Time (in s) |
+------+---------------------------+-------------+
| 1    | opt_out_usage             | 0           |
| 2    | default_platform          | 0           |
| 3    | ensure_git_status_clean   | 0           |
| 4    | app_store_connect_api_key | 0           |
| 💥   | upload_to_app_store       | 106         |
| 6    | reset_git_repo            | 0           |
+------+---------------------------+-------------+

```

</details>

**Comment by uaza** [comment]
I have also been experiencing the problem for three days, but also when I try to publish the app manually via the web interface, without Fastlane.

**Comment by ignite-daniel** [comment]
There is a recent update to fastlane and after I applied the update, I am now getting this error **_undefined method `first' for nil:NilClass_**

**Comment by kpowelltech** [comment]
We have noticed that this error is also affecting my team. We generate new apps every week, and it appears that this bug is only impacting the newer app builds. So far, we haven't observed this issue in the older app builds.  

It appears the Fastlane Deliver step is failing at uploading the ipa to App Store Connect.

**Comment by jakub-przy** [comment]
Hey all, 

Same exact issue on my end - so it's still happening :/

**Comment by demonguru18** [comment]
Downgrading Fastlane to **2.212.1** solves the issue. In the GemFile specify the version 
![image](https://user-images.githubusercontent.com/4347612/232877389-eff140c1-4d27-4d46-9a25-240562418bac.png)

** In the Fastfile set the **ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD** to **false**. I have added it to my **before_all** method
![image](https://user-images.githubusercontent.com/4347612/232877688-0bbc593f-1a21-499a-91ab-2471c09254ff.png)

**Comment by ignite-daniel** [comment]
@demonguru18 Thanks a lot. Your solution solved the issue for me.

**Comment by sonjz** [comment]
@kpowelltech wondering if you tried @demonguru18's fix?

i have the same scenario as you (can't release new app) but i haven't tried `ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD = false`.

i have a bunch of apps to send out and it is working on 2.212.1 and i don't want to mess with it, but i do have a new app i need to get out too.

**Comment by sonjz** [comment]
@jakub-przy this was for new apps as well?
for me `ITMSTRANSPORTER_FORCE_ITMS_PACKAGE_UPLOAD = true` is still working for existing apps.  i'll give it shot.

**Comment by jakub-przy** [comment]
Hey @sonjz 

Sorry, I forgot to mention this - I'm talking about the new apps specifically. Existing ones (version update workflows) worked fine all the time,

**Comment by jakub-przy** [comment]
Hey @sonjz 
>hoping the xcode upgrade doesn't force anything else, i know deadline coming for apr 26th...

In case you're using CircleCI - this is worth knowing (breaking changes 😬)
https://discuss.circleci.com/t/xcode-14-2-released-breaking-changes/46303

Otherwise I'm sorry it didn't help - I hope you'll find a solution soon.
Fastlane 2.212.1 + the transporter flag = false did the trick for me (CircleCI, intel mac executors, xcode:14.1.0.

**Comment by sonjz** [comment]
@jakub-przy thanks for clarification.  i'll update to xcode 14 as first step and hope i'm still good with fastlane 2.212.1 and turning off itms flag.  i'll keep thread posted.  most likely after apr 25th when all the things break.

**Comment by sonjz** [comment]
@jakub-przy got it to work with latest XCode + fastlane.  lost the functionality of using `price_tier: 0`, i'm setting that manually now.

**Comment by jakub-przy** [comment]
Hey, is there any news on an actual, permanent fix? Thanks!

**Comment by sonjz** [comment]
same still an issue in 2.113.0 when i put `price_tier 0` back in my `Deliverfile`

```
/Users/REDACTED/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0/gems/fastlane-2.213.0/deliver/lib/deliver/upload_price_tier.rb:24:in `upload': [!] undefined method `first' for nil:NilClass (NoMethodError)

```

**Comment by hkousha** [comment]
Does this issue exist in 2.214.0?

**Comment by PWhittle86** [comment]
Started experiencing this issue in 2.216.0 - never been an issue for me in the past.

**Comment by laiskajoonas** [comment]
Started getting this as well. Any solutions in sight?

**Comment by kamyarst** [comment]
Same issue here

**Comment by jwaldrip** [comment]
Same issue here as well. Going through the myriad of suggested fixes, but everything is halted at the moment.

**Comment by jwaldrip** [comment]
Any update here?

**Comment by anh1979** [comment]
Seems to be gone by itself again (got several error 500s in the last two weeks, now fastlane / API is proceeding)??
I didn't change anything on our side, though.

**Comment by kamyarst** [comment]
on our case, it's happening when Deliver tries to update app pricing.

**Comment by TySmith17** [comment]
I managed to fix this by upgrading ruby from 2.x o 3.x. Most of the other people who posted a ruby version in this thread seem to be using some version of ruby 2, so id recommend upgrading, especially as ruby 2 stopped being supported in March 2023.

**Comment by sittingbool** [comment]
I am having this issue when trying to create certificates and storing them in a git repo to be used on a pipeline. Is there an.update? Upgrading ruby did not work.

**Comment by jackstudd** [comment]
Hey, I had this exact same error, on the `latest_testflight_build_number` action. Turns out I had added a special suffix in my version for the builds in my branch, so the action was trying to fetch the Testflight build number of a version like `2.19.0-s4`. Removing the special suffix solved it for me.
