### ISSUE TITLE
undefined method `strip' when upload ipa to testflight

### ISSUE THREAD

**Issue by lina1** [fastlane/fastlane#14473]
### Issue Description

After I upgrade fastlane to 2.119.0, I got the following error. It happens when log in the AppStore Connect.
2.118.0 has the same issue. But 2.114.0 works fine.

##### Command executed

fastlane upload_to_testflight

##### Complete output when running fastlane, including the stack trace and command used

```
Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/tunes/tunes_client.rb:65:in `select_team': [31m[!] undefined method `strip' for 119432053:Fixnum[0m (NoMethodError)
from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/spaceship/lib/spaceship/tunes/spaceship.rb:35:in `select_team'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/pilot/lib/pilot/manager.rb:24:in `login'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/pilot/lib/pilot/manager.rb:16:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/pilot/lib/pilot/build_manager.rb:13:in `upload'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/actions/upload_to_testflight.rb:16:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:232:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:34:in `block in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.119.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'

**Comment by janpio** [comment]
Can you please post your `fastlane env` information? This will include the `Fastfile` you are using, so we know what `upload_to_testflight` actually is in your case.
