### ISSUE TITLE
Fastlane hangs then crashes with undefined method `prerelease=' for nil:NilClass

### ISSUE THREAD

**Issue by drekka** [fastlane/fastlane#9844]
I'm trying to learn fast lane, but so far it's not working. My current Fastfile is:

```
fastlane_require xcodebuild

desc "Increment framework version"
lane :build_framework do |lane|

xcodebuild(
	clean:true
)

end
```

After updating my ruby to 2.4 and all my gems, fast lane logs this:

```
[15:42:17]: ------------------------
[15:42:17]: --- Step: xcodebuild ---
[15:42:17]: ------------------------
[15:42:17]: For a more detailed xcodebuild log open /Users/derekclarkson/Library/Logs/fastlane/xcbuild/2017-07-25/92596/xcodebuild.log
[15:42:17]: $ set -o pipefail && xcodebuild  | tee '/Users/derekclarkson/Library/Logs/fastlane/xcbuild/2017-07-25/92596/xcodebuild.log' | xcpretty --color --simple
[15:42:18]: ▸ Building DigitalID/DigitalID-iOS [(Release)]
[15:42:18]: ▸ Check Dependencies
[15:42:18]: ▸ Running script 'Turn tags into warnings'
[15:42:18]: ▸ Build Succeeded
[15:42:18]: Installing Ruby gem '▸ Building DigitalID/DigitalID-iOS [(Release)]
▸ Check Dependencies
▸ Running script 'Turn tags into warnings'
▸ Build Succeeded
'...
```

Then it hangs for two minutes before crashing out:

```
[15:44:39]: Found gem "" instead of the required name "▸ Building DigitalID/DigitalID-iOS [(Release)]
▸ Check Dependencies
▸ Running script 'Turn tags into warnings'
▸ Build Succeeded
"

Looking for related GitHub issues on fastlane/fastlane...

➡️  live_version not found
    https://github.com/fastlane/fastlane/issues/3489 [closed] 6 💬
    22 Sep 2016

🔗  You can ⌘ + double-click on links to open them directly in your browser.
/Users/derekclarkson/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:470:in `resolve_dependencies': [!] undefined method `prerelease=' for nil:NilClass (NoMethodError)
	from /Users/derekclarkson/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/commands/install_command.rb:194:in `install_gem'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fastlane_require.rb:36:in `install_gem_if_needed'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fast_file.rb:190:in `fastlane_require'
	from Fastfile:2:in `parsing_binding'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fast_file.rb:54:in `eval'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fast_file.rb:54:in `block in parse'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fast_file.rb:43:in `chdir'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fast_file.rb:43:in `parse'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/fast_file.rb:33:in `initialize'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/lane_manager.rb:12:in `new'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/lane_manager.rb:12:in `cruise_lane'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/gems/fastlane-2.48.0/bin/fastlane:20:in `<top (required)>'
	from /Users/derekclarkson/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `load'
	from /Users/derekclarkson/.rvm/rubies/ruby-2.4.0/bin/fastlane:23:in `<main>'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `eval'
	from /Users/derekclarkson/.rvm/gems/ruby-2.4.0@global/bin/ruby_executable_hooks:15:in `<main>'

```

I have no idea what's wrong. What do I fix?

**Comment by drekka** [comment]
Okies. Here it is:

[15:58:58]: For more information, check out https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
[15:59:00]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                       |
| --------------------------- | ------------------------------------------- |
| OS                          | 10.12.6                                     |
| Ruby                        | 2.4.0                                       |
| Bundler?                    | false                                       |
| Git                         | git version 2.11.0 (Apple Git-81)           |
| Installation Source         | ~/.rvm/rubies/ruby-2.4.0/bin/fastlane       |
| Host                        | Mac OS X 10.12.6 (16G29)                    |
| Ruby Lib Dir                | ~/.rvm/rubies/ruby-2.4.0/lib                |
| OpenSSL Version             | OpenSSL 1.1.0f  25 May 2017                 |
| Is contained                | false                                       |
| Is homebrew                 | false                                       |
| Is installed via Fabric.app | false                                       |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/ |
| Xcode Version               | 8.3.3                                       |


### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_AU.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |


### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby

fastlane_require xcodebuild

desc "Increment framework version"
lane :build_framework do |lane|


xcodebuild(
	clean:true
)

end```
</details>

**No Appfile found**


### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.48.0  | ✅ Up-To-Date  |


### Loaded fastlane plugins:

**No plugins Loaded**


<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.1.2        |
| executable-hooks          | 1.3.2        |
| bundler-unload            | 1.0.2        |
| rubygems-bundler          | 1.4.4        |
| bundler                   | 1.15.3       |
| io-console                | 0.4.6        |
| slack-notifier            | 1.5.1        |
| CFPropertyList            | 2.3.5        |
| claide                    | 1.0.2        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.3.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| excon                     | 0.57.1       |
| faraday                   | 0.12.2       |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| uber                      | 0.1.0        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.0.2        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| jwt                       | 1.5.6        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| google-api-client         | 0.12.0       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.2.1        |
| faraday_middleware        | 0.11.0.1     |
| json                      | 2.1.0        |
| openssl                   | 2.0.4        |
</details>


*generated on:* **2017-07-25**
</details>

**Comment by mpirri** [comment]
@drekka The problem here is that you need to wrap `xcodebuild` in quotes on line 1 of your script. So, instead of having:
```
fastlane_require xcodebuild
```
You should have:
```
fastlane_require "xcodebuild"
```

If you don't do this (and this is the interesting part!), it will actually *run* `xcodebuild` as part of the `fastlane_require` line! And that produces weird output like the `Installing Ruby gem '▸ Building DigitalID/DigitalID-iOS [(Release)]` line you saw.

I hope this helps, please let us know if you have other questions about _fastlane_! 🚀

**Comment by drekka** [comment]
ok, that was a WTF moment. Thanks, I would never have figured that out.
