### ISSUE TITLE
How to build a React Native app with `gym` on Travis

### ISSUE THREAD

**Issue by ncmd** [fastlane/fastlane#14075]
After spending about ~1.5 weeks getting travis to work nicely with fastlane deployment, here are my solutions....

fyi works on 2.114.0

# 1. Supports only version React native 57.8
- Make sure react-native version 57.8 is install in package.json file.
- Error if built with react-native 58.rc...:
```
❌  ld: symbol(s) not found for architecture x86_64
❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)
** BUILD FAILED **
```
- Always build with YARN for travis and this project, or else all builds with gym will fail!

# 2. React-native does not,generate main.jsbundle
- Add it with XCODE: https://github.com/facebook/react-native/issues/18313#issuecomment-421551538
- Solution:
```
npm install react-native-cli -g
cd <root of react native project>
react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'
```
- Common Error:
```
❌  error: File /Users/travis/Library/Developer/Xcode/DerivedData/publicreactnativeapp-cmstzkswapckofaljfpwelwacbjr/Build/Intermediates.noindex/ArchiveIntermediates/publicreactnativeapp/BuildProductsPath/Release-iphoneos/publicreactnativeapp.app/main.jsbundle does not exist. This must be a bug with
```
# 3. In Xcode, add bundle react native code and images
- Open Xcode > Click Project > Build Phases > bundle react native code and images; add the following in the "Shell:/bin/sh" section:
```
export NODE_BINARY=node
../node_modules/react-native/scripts/react-native-xcode.sh
```
- Common Error:
```
** ARCHIVE FAILED **
The following build commands failed:
PhaseScriptExecution Bundle\ React\ Native\ code\ and\ images /Users/travis/Library/Developer/Xcode/DerivedData/publicreactnativeapp-cmstzkswapckofaljfpwelwacbjr/Build/Intermediates.noindex/ArchiveIntermediates/publicreactnativeapp/IntermediateBuildFilesPath/publicreactnativeapp.build/Release-iphoneos/publicreactnativeapp.build/Script-00DD1BFF1BD5951E006B06BC.sh
(1 failure)
[21:59:52]: Exit status: 65
```
# 4. Generating a NEW spaceship FASTLANE_SESSION for every before pushing git commit
```
cd projectname/ios
bundle exec fastlane spaceauth -u <your_email_address_for_apple_account>
```
copy the first part. paste it to a file.txt
In your travis.yml file:
```
# Setting fastlane session to bypass 2-factor for apple account; this session much be changed every build or else it will fail whole build process
        - echo $FASTLANE_SESSION
        - var=$(cat ./session.txt) && export FASTLANE_SESSION=$var
# Confirm session environment variable is set
        - echo $FASTLANE_SESSION
```

# 5. Next is setting up the Fastfile lanes....
```
lane :travisgym do |values|

    setup_travis

    sync_code_signing(
      type: "appstore",
      git_url:"https://github.com/ncmd/public-fastlane-certificates",
      keychain_name:"fastlane_tmp_keychain"
      )

     increment_build_number(
      xcodeproj: "./publicreactnativeapp.xcodeproj"
      )

    build_app(
      scheme: "publicreactnativeapp",
      workspace: "publicreactnativeapp.xcworkspace",
      include_bitcode: false,
      export_method: "app-store",
      export_options: {
        uploadBitcode: false,
        uploadSymbols: true,
        compileBitcode: false,
        provisioningProfiles: { 
          "com.ncmd.publicreactnativeapp" => "match AppStore com.ncmd.publicreactnativeapp"
        }
      }
    )
  end
```

# 6. Finally the travis.yml file
```
matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode10.1
      xcode_project: ./publicreactnativeapp.xcodeproj
      xcode_scheme: publicreactnativeapp
      node_js: false
      sudo: required
      env:
        # required by fastlane
        - LC_ALL=en_US.UTF-8
        - LANG=en_US.UTF-8
        # increase node space just in case
        - NODE_OPTIONS="--max-old-space-size=4096"
      before_install:
        # Setting up environment similar to local environment
        - nvm install 11.6
        - rvm install 2.6.0
        - travis_retry npm install -g yarn
        - rvm --default use 2.6.0
        - brew update
        - gem update --system
        - gem install bundler
        - gem install fastlane
        - pwd
        - ls ~/.ssh/
# Decrypt key to download certificate from a private certificate repository
        - cd ./ios && openssl aes-256-cbc -K $encrypted_135108afd44f_key -iv $encrypted_135108afd44f_iv -in deploy_key.enc -out ~/.ssh/deploy_key -d
        - cp deploy_key.pub ~/.ssh/deploy_key.pub
        - ls ~/.ssh/
        - echo -e "Host github.com\n\tHostName github.com\n\tncmd git\n\tIdentityFile ~/.ssh/deploy_key\n" >> ~/.ssh/config
        - ssh-keyscan github.com >> ~/.ssh/known_hosts
        - chmod 600 ~/.ssh/deploy_key
        - cd ..
      install:
        # using yarn instead of npm install because project would not build properly in travis
        - pwd
        - yarn install
        # required to use react-native 
        - npm install -g react-native-cli
        # Adds missing main.jsbundle file when react-native project is created
        - react-native bundle --entry-file='index.js' --bundle-output='./ios/main.jsbundle' --dev=false --platform='ios'
      script:
        - pwd
        - cd ./ios/
        # Install all gemfile requirements and allows faster fastlane performance
        - bundle install
        # Setting fastlane session to bypass 2-factor for apple account; this session much be changed every build or else it will fail whole build process
        - echo $FASTLANE_SESSION
        - var=$(cat ./session.txt) && export FASTLANE_SESSION=$var
        # Confirm session environment variable is set
        - echo $FASTLANE_SESSION
        - bundle update
        - nohup react-native run-ios &
        # - bundle exec fastlane ios travisenable
        - ls /Users/travis/Library/Keychains/
        # Silence gym in the background or else logs will pass 10000 and travis will force end the build
        - nohup bundle exec fastlane ios travisgym &
        - pwd
        # to keep build alive, set a for loop for 10 minutes
        - for i in $(seq 1 10); do sleep 60; echo $i; done
        # You should see "publicreactnativeapp.app.dSYM.zip and publicreactnativeapp.ipa"
        - ls
        # now upload your build (If this part failed that means you didnt generate a new session token to pass 2factor
        - bundle exec fastlane ios travisupload
```
Hopes this helps someone save time and not 2+ weeks of troubleshooting...
