### ISSUE TITLE
Failing to run fastlane after updating to 1.96 from 1.95

### ISSUE THREAD

**Issue by itaydressler** [fastlane/fastlane#5221]
Trying to run 'fastlane' and getting this output - 
```
Tops-MacBook-Pro:GONG Build itaydressler$ fastlane
[15:51:32]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

Looking for related GitHub issues on fastlane/fastlane...

/Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:99:in `rescue in show_github_issues': undefined method `error' for Commander::UI:Module (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:89:in `show_github_issues'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:43:in `rescue in run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.48.0/lib/fastlane_core/ui/fastlane_runner.rb:50:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/commands_generator.rb:244:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/commands_generator.rb:20:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/lib/fastlane/cli_tools_distributor.rb:47:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.96.0/bin/fastlane:5:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
Tops-MacBook-Pro:GONG Build itaydressler$ 
```
Just updated to the latest build (1.96) and started getting this issue. 
I'm not calling a specific lane, just trying to get fastlane working.

**Comment by vpolouchkine** [comment]
Can you please format your issue per https://github.com/fastlane/fastlane/blob/master/ISSUE_TEMPLATE.md? Thanks!
