### ISSUE TITLE
SnapshotHelper.swift from fastlane 2.55.0 fails to compile using Xcode 8

### ISSUE THREAD

**Issue by afh** [fastlane/fastlane#10231]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

`SnapshotHelper.swift` fails to compile using Xcode Version 8.3.2 (8E2002) with error:
```
fastlane/SnapshotHelper.swift:131:34: error: value of type 'XCUIElementQuery' has no member 'firstMatch'
            let screenshot = app.windows.firstMatch.screenshot()
```

⚠️ [`firstMatch` was added with Xcode 9](https://developer.apple.com/documentation/xctest/xcuielementtypequeryprovider/2902250-firstmatch) and is not available with previous versions of Xcode:

https://github.com/fastlane/fastlane/blob/f410f2a6d9d20ae8e6747db978cae7142a03d781/snapshot/lib/assets/SnapshotHelper.swift#L131

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

[18:58:22]: [33mGenerating fastlane environment output, this might take a few seconds...[0m
<details><summary>🚫 fastlane environment 🚫</summary>

### Stack

| Key                         | Value                                                           |
| --------------------------- | --------------------------------------------------------------- |
| OS                          | 10.12.6                                                         |
| Ruby                        | 2.0.0                                                           |
| Bundler?                    | true                                                            |
| Git                         | git version 2.14.1                                              |
| Installation Source         | ~/Work/vendor/bundle/ruby/2.0.0/bin/fastlane |
| Host                        | Mac OS X 10.12.6 (16G29)                                        |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib  |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                     |
| Is contained                | false                                                           |
| Is homebrew                 | false                                                           |
| Is installed via Fabric.app | false                                                           |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                     |
| Xcode Version               | 8.3.2                                                           |

### System Locale

| Error                       |
| --------------------------- |
| No Locale with UTF8 found 🚫 |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://docs.fastlane.tools/actions
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "2.7.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
  end

  desc "Run integration tests"
  lane :integration do
    snapshot(devices: ['iPhone 7'])
  end

  desc "Create new screenshots to verify the Link iOS flow"
  desc "Additionally, this will add device frames around the screenshots"
  lane :screenshots do
    snapshot(devices: ['iPhone 7', 'iPhone SE', 'iPad Pro (9.7 inch)'])
    frameit(white: true, path: './screenshots')
  end

 #desc "Runs all the tests"
 #lane :test do
 #  scan
 #end

 #desc "Submit a new Beta Build to Apple TestFlight"
 #desc "This will also make sure the profile is up to date"
 #lane :beta do
 #  # match(type: "appstore") # more information: https://codesigning.guide
 #  gym # Build your app - more options available
 #  pilot

 #  # sh "your_script.sh"
 #  # You can also use other beta testing services here (run `fastlane actions`)
 #end

 #desc "Deploy a new version to the App Store"
 #lane :release do
 #  # match(type: "appstore")
 #  # snapshot
 #  gym # Build your app - more options available
 #  deliver(force: true)
 #  # frameit
 #end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful
    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://docs.fastlane.tools/actions

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby


# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.55.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| bundler                   | 1.15.4       |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.4       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-09-01**
</details>
[18:58:23]: [32mOpen https://github.com/fastlane/fastlane/issues/new to submit a new issue ✅[0m

**Comment by dayjer** [comment]
Stuck here as well, can't use Xcode 9 due to https://github.com/fastlane/fastlane/issues/10259 and can't use Xcode 8.

**Comment by KrauseFx** [comment]
Oh interesting, do you mind submitting a PR fixing this? :)

**Comment by afh** [comment]
I may find time to have a look, yet I prefer the person introducing the changes revise and amend them.

**Comment by tkanzakic** [comment]
The helper class for Xcode 8 is still in the repo as [SnapshotHelperXcode8.swift](https://github.com/fastlane/fastlane/blob/master/snapshot/lib/assets/SnapshotHelperXcode8.swift). 

I think we have two options:
1. update the documentation to point to the appropriate file depending on the Xcode version being used and let developers decide.
2. have only one file with the implementation for both Xcode8.x and Xcode9+ (you can see [draft in here](https://github.com/fastlane/fastlane/compare/master...tkanzakic:use-appropriate-snapshot-impl?expand=1)). As I commented in the draft the main issue I see with this option is that AFAIK we have to rely on the compiler version to detect the current Xcode version, which is going to fail is some scenarios.

**Comment by funnel20** [comment]
There is still no solution. 
However, I found a work-around to at least run on Xcode 8.3.3 with the previous version of the Helper file. Use `--skip_helper_version_check` when starting snapshot to continue without the error to update: 
`fastlane snapshot --skip_helper_version_check y`
