### PR TITLE
[deliver] fix app previews always running during usage.

### LINKED ISSUE #29983: 2.233.0: sync_app_previews runs unconditionally during upload_metadata, crashes when no editable App Store version exists
### New Regression Checklist

     - [x] Updated fastlane to the latest version
     - [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
     - [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
     - [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

     ### Regression Information
     - Breaking version: `2.233.0`
     - Last working version: `2.232.2`

     ### Regression Description

     `deliver` crashes during TestFlight-only uploads (no metadata, no screenshots, no review submission) when there is no editable App Store version in App Store Connect. The crash is triggered by the new App Preview video
     upload support added in #29831.

     **Expected behavior:** With `--skip_metadata --skip_screenshots --skip_app_version_update` and `submit_for_review: false`, deliver should upload the binary and exit cleanly. This worked on 2.232.2 and every prior 2.232.x
      release.

     **Actual behavior:** Upload succeeds, but afterwards deliver crashes with `NoMethodError: undefined method 'get_app_store_version_localizations' for nil` from `sync_app_previews.rb:23`. Exit code 1 fails the CI build.

     **Root cause** (traced through the source):

     1. `deliver/lib/deliver/runner.rb` — `run` calls `upload_metadata` unconditionally. There is no `skip_metadata` guard in front of it; `skip_metadata` only affects behavior *inside* `UploadMetadata#upload`, not whether
     sibling blocks run.
     2. `deliver/lib/deliver/runner.rb:162` — the new block added in #29831:
        ```ruby
        if options[:app_previews_path]
          previews = Deliver::SyncAppPreviews.new(...)
          previews.sync_from_path
        end
        ```
     3. `deliver/lib/deliver/detect_values.rb:61` — `find_folders` silently populates the option:
        ```ruby
        options[:app_previews_path] ||= File.join(containing, 'app-previews')
        ```
     4. `deliver/lib/deliver/detect_values.rb:67` — `ensure_folders_created` then runs `FileUtils.mkdir_p(options[:app_previews_path])`, so the directory always exists and `validate_path!` in sync_app_previews always passes.
     5. `deliver/lib/deliver/sync_app_previews.rb:23` — `editable_version.get_app_store_version_localizations` NPEs because `@app.get_edit_app_store_version` returns nil when there's no version in "Prepare for Submission" (a
     normal, extremely common state for TestFlight-only workflows).

     Net effect: the `if options[:app_previews_path]` guard at runner.rb:162 is effectively always true, because `detect_values` populates and creates the path whether or not the user wants previews. Users who never intended
     to use app previews (and have no ASC version open) are now forced through the preview sync code path and crash.

     **Impact:** any fastlane consumer whose flow is "upload binary to TestFlight, don't touch App Store metadata" will hit this on first run after upgrading to 2.233.0. This includes most Bitrise / CI TestFlight pipelines
     using the official "Deploy to App Store Connect with Deliver" step.

     **Suggested fixes** (either alone would resolve):
     - Gate the new block at runner.rb:162 behind `!options[:skip_metadata]`.
     - Only consider `app_previews_path` "set" when the user explicitly provides it; don't auto-populate it in `detect_values#find_folders` and don't auto-create the directory. Or: treat an empty auto-created dir as "no
     previews, skip" and short-circuit *before* the `editable_version` call.
     - Defensive: in `sync_app_previews.rb:23`, check `editable_version` for nil and return with a warning instead of NPEing.

     **Workaround:** pin fastlane to `2.232.2` in `Gemfile`.

     ##### Complete output when running fastlane, including the stack trace and command used

     <details>
       <pre>
     4. `deliver/lib/deliver/detect_values.rb:67` — `ensure_folders_created` then runs `FileUtils.mkdir_p(options[:app_previews_path])`, so the directory always exists and `validate_path!` in sync_app_previews always passes.
     5. `deliver/lib/deliver/sync_app_previews.rb:23` — `editable_version.get_app_store_version_localizations` NPEs because `@app.get_edit_app_store_version` returns nil when there's no version in "Prepare for Submission" (a
     normal, extremely common state for TestFlight-only workflows).

     Net effect: the `if options[:app_previews_path]` guard at runner.rb:162 is effectively always true, because `detect_values` populates and creates the path whether or not the user wants previews. Users who never intended
     to use app previews (and have no ASC version open) are now forced through the preview sync code path and crash.

     **Impact:** any fastlane consumer whose flow is "upload binary to TestFlight, don't touch App Store metadata" will hit this on first run after upgrading to 2.233.0. This includes most Bitrise / CI TestFlight pipelines
     using the official "Deploy to App Store Connect with Deliver" step.

     **Suggested fixes** (either alone would resolve):
     - Gate the new block at runner.rb:162 behind `!options[:skip_metadata]`.
     - Only consider `app_previews_path` "set" when the user explicitly provides it; don't auto-populate it in `detect_values#find_folders` and don't auto-create the directory. Or: treat an empty auto-created dir as "no
     previews, skip" and short-circuit *before* the `editable_version` call.
     - Defensive: in `sync_app_previews.rb:23`, check `editable_version` for nil and return with a warning instead of NPEing.

     **Workaround:** pin fastlane to `2.232.2` in `Gemfile`.

     ##### Complete output when running fastlane, including the stack trace and command used

     <details>
       <pre>
     $ fastlane "deliver" "--api_key_path" "..." "--precheck_include_in_app_purchases" "false" "--app" "..." "--team_name" "..." "--ipa" "..." "--skip_screenshots" "--skip_metadata" "--skip_app_version_update" "--force"
     "--platform" "ios"

     [binary upload succeeds]

     /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/sync_app_previews.rb:23:in `sync_from_path': [!] undefined method `get_app_store_version_localizations' for nil
     (NoMethodError)

           localizations = editable_version.get_app_store_version_localizations
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/runner.rb:170:in `upload_metadata'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/runner.rb:62:in `run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/fastlane/lib/fastlane/cli_tools_distributor.rb:124:in `take_off'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/bin/fastlane:23:in `<top (required)>'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/bin/fastlane:25:in `load'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/bin/fastlane:25:in `<main>'
       </pre>
     </details>

### PR DESCRIPTION
**Pull request by iBotPeaches**
### Problem

App Previews is gated by the config parameter `app_previews_path`, which was silently populated like it was an output directory. So the logic always ran. Which would normally just "no-op" since no videos, but it first captures version number. If the IPA is purely internal and no public facing versions - it crashes.

### Solution
Gate App Previews only be the existence of the parameter. This make using App Previews "opt in".

fixes: #29983

### CODE REVIEW

File: deliver/lib/deliver/sync_app_previews.rb [hunk 1]
```diff
@@ -14,13 +14,20 @@ def initialize(app:, platform:, app_previews_path:, preview_frame_time_code: nil
...
       @overwrite = overwrite_preview_videos
+
+      validate_path!
     end
 
     def sync_from_path
       UI.important("Uploading App Preview videos...")
-      validate_path!
 
-      localizations = editable_version.get_app_store_version_localizations
```
Comment (taquitos) [inline deliver/lib/deliver/sync_app_previews.rb:23]: Seems unrelated but looks ok

**Review by taquitos — APPROVED** [review]

File: deliver/spec/detect_values_spec.rb [hunk 2]
```diff
@@ -11,40 +11,46 @@
...
 
         it 'sets up metadata folder in fastlane folder' do
+          value_detector.find_folders(options)
           expect(options[:metadata_path]).to eq('./fastlane/metadata')
         end
 
-        it 'sets up app previews folder in fastlane folder' do
-          expect(options[:app_previews_path]).to eq('./fastlane/app-previews')
+        it 'does not automatically set up app previews folder in fastlane folder even if it exists' do
+          FileUtils.mkdir_p('./fastlane/app-previews')
```
Comment (lacostej) [inline deliver/spec/detect_values_spec.rb]: Creating and removing folders within tests is a bit brittle.

unless you want to mock the file system
* you could add an extra desc/before/after to ensure they get taken care of by rspsec
* you could also use a test specific temp folder (as in Deliver::UploadMetadata spec)

File: deliver/lib/deliver/sync_app_previews.rb (hunk 1 above)
Comment (iBotPeaches) [reply deliver/lib/deliver/sync_app_previews.rb:23]: yeah good call out. I first thought adding some defensive logic in case you can't get a version, but now that its probably gated - it was probably overkill.

File: deliver/spec/detect_values_spec.rb (hunk 2 above)
Comment (iBotPeaches) [reply deliver/spec/detect_values_spec.rb]: makes sense. I adapted following the pattern of UploadMetadata (spawning a temp dir, working in there, cleaning up in after)

**Review by ccaruceru — APPROVED** [review]
this lgtm. the only suggestion I have is to remove the tests about `app_previews_path` since they became... irrelevant.
