### ISSUE TITLE
2.233.0: sync_app_previews runs unconditionally during upload_metadata, crashes when no editable App Store version exists

### ISSUE THREAD

**Issue by awchang56** [fastlane/fastlane#29983]
### New Regression Checklist

     - [x] Updated fastlane to the latest version
     - [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
     - [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
     - [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

     ### Regression Information
     - Breaking version: `2.233.0`
     - Last working version: `2.232.2`

     ### Regression Description

     `deliver` crashes during TestFlight-only uploads (no metadata, no screenshots, no review submission) when there is no editable App Store version in App Store Connect. The crash is triggered by the new App Preview video
     upload support added in #29831.

     **Expected behavior:** With `--skip_metadata --skip_screenshots --skip_app_version_update` and `submit_for_review: false`, deliver should upload the binary and exit cleanly. This worked on 2.232.2 and every prior 2.232.x
      release.

     **Actual behavior:** Upload succeeds, but afterwards deliver crashes with `NoMethodError: undefined method 'get_app_store_version_localizations' for nil` from `sync_app_previews.rb:23`. Exit code 1 fails the CI build.

     **Root cause** (traced through the source):

     1. `deliver/lib/deliver/runner.rb` — `run` calls `upload_metadata` unconditionally. There is no `skip_metadata` guard in front of it; `skip_metadata` only affects behavior *inside* `UploadMetadata#upload`, not whether
     sibling blocks run.
     2. `deliver/lib/deliver/runner.rb:162` — the new block added in #29831:
        ```ruby
        if options[:app_previews_path]
          previews = Deliver::SyncAppPreviews.new(...)
          previews.sync_from_path
        end
        ```
     3. `deliver/lib/deliver/detect_values.rb:61` — `find_folders` silently populates the option:
        ```ruby
        options[:app_previews_path] ||= File.join(containing, 'app-previews')
        ```
     4. `deliver/lib/deliver/detect_values.rb:67` — `ensure_folders_created` then runs `FileUtils.mkdir_p(options[:app_previews_path])`, so the directory always exists and `validate_path!` in sync_app_previews always passes.
     5. `deliver/lib/deliver/sync_app_previews.rb:23` — `editable_version.get_app_store_version_localizations` NPEs because `@app.get_edit_app_store_version` returns nil when there's no version in "Prepare for Submission" (a
     normal, extremely common state for TestFlight-only workflows).

     Net effect: the `if options[:app_previews_path]` guard at runner.rb:162 is effectively always true, because `detect_values` populates and creates the path whether or not the user wants previews. Users who never intended
     to use app previews (and have no ASC version open) are now forced through the preview sync code path and crash.

     **Impact:** any fastlane consumer whose flow is "upload binary to TestFlight, don't touch App Store metadata" will hit this on first run after upgrading to 2.233.0. This includes most Bitrise / CI TestFlight pipelines
     using the official "Deploy to App Store Connect with Deliver" step.

     **Suggested fixes** (either alone would resolve):
     - Gate the new block at runner.rb:162 behind `!options[:skip_metadata]`.
     - Only consider `app_previews_path` "set" when the user explicitly provides it; don't auto-populate it in `detect_values#find_folders` and don't auto-create the directory. Or: treat an empty auto-created dir as "no
     previews, skip" and short-circuit *before* the `editable_version` call.
     - Defensive: in `sync_app_previews.rb:23`, check `editable_version` for nil and return with a warning instead of NPEing.

     **Workaround:** pin fastlane to `2.232.2` in `Gemfile`.

     ##### Complete output when running fastlane, including the stack trace and command used

     <details>
       <pre>
     4. `deliver/lib/deliver/detect_values.rb:67` — `ensure_folders_created` then runs `FileUtils.mkdir_p(options[:app_previews_path])`, so the directory always exists and `validate_path!` in sync_app_previews always passes.
     5. `deliver/lib/deliver/sync_app_previews.rb:23` — `editable_version.get_app_store_version_localizations` NPEs because `@app.get_edit_app_store_version` returns nil when there's no version in "Prepare for Submission" (a
     normal, extremely common state for TestFlight-only workflows).

     Net effect: the `if options[:app_previews_path]` guard at runner.rb:162 is effectively always true, because `detect_values` populates and creates the path whether or not the user wants previews. Users who never intended
     to use app previews (and have no ASC version open) are now forced through the preview sync code path and crash.

     **Impact:** any fastlane consumer whose flow is "upload binary to TestFlight, don't touch App Store metadata" will hit this on first run after upgrading to 2.233.0. This includes most Bitrise / CI TestFlight pipelines
     using the official "Deploy to App Store Connect with Deliver" step.

     **Suggested fixes** (either alone would resolve):
     - Gate the new block at runner.rb:162 behind `!options[:skip_metadata]`.
     - Only consider `app_previews_path` "set" when the user explicitly provides it; don't auto-populate it in `detect_values#find_folders` and don't auto-create the directory. Or: treat an empty auto-created dir as "no
     previews, skip" and short-circuit *before* the `editable_version` call.
     - Defensive: in `sync_app_previews.rb:23`, check `editable_version` for nil and return with a warning instead of NPEing.

     **Workaround:** pin fastlane to `2.232.2` in `Gemfile`.

     ##### Complete output when running fastlane, including the stack trace and command used

     <details>
       <pre>
     $ fastlane "deliver" "--api_key_path" "..." "--precheck_include_in_app_purchases" "false" "--app" "..." "--team_name" "..." "--ipa" "..." "--skip_screenshots" "--skip_metadata" "--skip_app_version_update" "--force"
     "--platform" "ios"

     [binary upload succeeds]

     /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/sync_app_previews.rb:23:in `sync_from_path': [!] undefined method `get_app_store_version_localizations' for nil
     (NoMethodError)

           localizations = editable_version.get_app_store_version_localizations
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/runner.rb:170:in `upload_metadata'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/runner.rb:62:in `run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/commands_generator.rb:82:in `block (2 levels) in run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/commands_generator.rb:187:in `run'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/deliver/lib/deliver/commands_generator.rb:18:in `start'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/fastlane/lib/fastlane/cli_tools_distributor.rb:124:in `take_off'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/lib/ruby/gems/3.3.0/gems/fastlane-2.233.0/bin/fastlane:23:in `<top (required)>'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/bin/fastlane:25:in `load'
         from /Users/vagrant/.asdf/installs/ruby/3.3.5/bin/fastlane:25:in `<main>'
       </pre>
     </details>

**Comment by iBotPeaches** [comment]
Able to fix issue report? One massive code block and tough to understand.

**Comment by awchang56** [comment]
Sorry about the formatting — fixed the body, it had a bunch of leading spaces on every line so GitHub was rendering the whole thing as one code block.

On fastlane env: the failing build was on a Bitrise macOS runner (Xcode 26, Ruby 3.3.5 via asdf, fastlane 2.233.0 installed by the Bitrise deploy step). I've since pinned to 2.232.2 so I can't easily capture env on a currently-broken build.

**Comment by iBotPeaches** [comment]
Okay I see. Since `detect_values` build the path and `ensure_folders_created` makes it, so it always runs. 

@ccaruceru - able to help out with a fix here? I believe its a good find that we need a quick escape if theres no contents or something to prevent the calls causing this issue.

**Comment by alainib** [comment]
we have the same error

any fixes ?

**Comment by ccaruceru** [comment]
@iBotPeaches I'm away from my computer until end of the week. Can you make a quick fix please? 🙏🏻 

I'm okay for the option of stopping the creation of the default output dir to skip the upload.

**Comment by iBotPeaches** [comment]
@ccaruceru - sounds good. I did a quick sample - https://github.com/fastlane/fastlane/pull/29989, will free up more in middle of day to test it out.

**Comment by alainib** [comment]
what can we do until next release please ? i cannot push new version

**Comment by iBotPeaches** [comment]
@alainib - Revert to last version or test out my patch and report back.

Gemfile
```
gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'issue-29983'
```

then

```
bundle update
```

**Comment by alainib** [comment]
> [@alainib](https://github.com/alainib) - Revert to last version or test out my patch and report back.
> 
> Gemfile
> 
> ```
> gem 'fastlane', git: 'https://github.com/fastlane/fastlane.git', branch: 'issue-29983'
> ```
> 
> then
> 
> ```
> bundle update
> ```

thanks a lot it worked !!

**Comment by alainib** [comment]
do you know when a new version will be released with the fix of @iBotPeaches  ?

thanks
