### ISSUE TITLE
[!] undefined method `login' for Spaceship:Module

### ISSUE THREAD

**Issue by mjgallag** [fastlane/fastlane#11618]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

Broke in `2.75.0` and is still broken in `2.77.1`, works in `2.74.1`.

##### Complete output when running fastlane, including the stack trace and command used

```
[!] undefined method `login' for Spaceship:Module
  Fastfile:33:in `get_profile_info'
  Fastfile:188:in `block (2 levels) in parsing_binding'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.77.1/bin/fastlane:20:in `<top (required)>'
  /usr/local/bin/fastlane:22:in `load'
  /usr/local/bin/fastlane:22:in `<top (required)>'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.15.1                                             |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C205)                                      |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.77.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-versioning | 0.3.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.0.0        |
| bundler                    | 1.16.1       |
| io-console                 | 0.4.5        |
| CFPropertyList             | 2.3.6        |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| colored                    | 1.2          |
| colored2                   | 3.1.2        |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.5        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| dotenv                     | 2.2.1        |
| excon                      | 0.60.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.13.1       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.12.2       |
| fastimage                  | 2.1.1        |
| gh_inspector               | 1.0.3        |
| jwt                        | 2.1.0        |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.13.1       |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.2        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| google-api-client          | 0.13.6       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.4.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.6.4        |
| tty-cursor                 | 0.5.0        |
| tty-spinner                | 0.8.0        |
| word_wrap                  | 1.0.0        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.4        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| xcpretty-travis-formatter  | 1.0.0        |
| fastlane-plugin-versioning | 0.3.3        |
</details>

*generated on:* **2018-01-18**
</details>

**Comment by taquitos** [comment]
This is showing an error in your `Fastfile`, if you post the contents of your `Fastfile`, we should be able to help you track it down 😄

**Comment by sainttail** [comment]
I got the same error

This is my Fastfile

```
#!/usr/bin/ruby

###############################################################################
#
# Eko iOS Fastfile
#
###############################################################################
fastlane_require 'aws-sdk'

# load env using file
fastlane_require 'dotenv'
Dotenv.load '../.env'

fastlane_require 'json'
fastlane_require 'xcodeproj'
fastlane_require 'fileutils'

default_platform :ios

opt_out_usage
skip_docs

platform :ios do
 
  desc "Create Push Certificate on Server both APNS and VOIP"
  lane :create_push_certificate do
    Spaceship.login
  end
end
```

And what i am doing is 
`~/D/e/IOSEko ❯❯❯ fastlane create_push_certificate`

```
Fastfile:27:in `block (2 levels) in parsing_binding': [!] undefined method `login' for Spaceship:Module (NoMethodError)
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/fastlane/lib/fastlane/cli_tools_distributor.rb:98:in `take_off'
	from /Users/sainttail/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/gems/fastlane-2.80.0/bin/fastlane:20:in `<top (required)>'
	from /Users/sainttail/.rbenv/versions/2.3.3/bin/fastlane:22:in `load'
	from /Users/sainttail/.rbenv/versions/2.3.3/bin/fastlane:22:in `<main>'
```

**Comment by KrauseFx** [comment]
Try `Spaceship::Tunes.login` and `Spaceship::Portal.login` instead 👍

**Comment by minuscorp** [comment]
I've been needing to `require "spaceship"` in recent versions of fastlane when calling `Spaceship` methods!

**Comment by KrauseFx** [comment]
Yep, you have to require spaceship before using it 👍

**Comment by sainttail** [comment]
OK `require 'spaceship'` solve the problem thanks!
