### ISSUE TITLE
macOS unit tests crashing - undefined method `each' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by Cyberbeni** [fastlane/fastlane#15905]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

running test  on macOS fails at the start with this error:

```
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:35:in `test_app': undefined method `each' for nil:NilClass (NoMethodError)
```

According to my test history, it was working in 2.137.0 and not working in 2.139.0

##### Command executed

https://github.com/Cyberbeni/TypedNotificationCenter/tree/post-same-typed
fails:
fastlane scan --scheme "TypedNotificationCenter macOS" --verbose
runs correctly:
fastlane scan --scheme "TypedNotificationCenter iOS" --verbose

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre> fastlane scan --scheme "TypedNotificationCenter macOS" --verbose
[✔] 🚀
[23:40:04]: Get started using a Gemfile for fastlane https://docs.fastlane.tools/getting-started/ios/setup/#use-a-gemfile
INFO [2020-01-15 23:40:05.78]: $ xcodebuild -showBuildSettings -scheme TypedNotificationCenter\ macOS -project ./TypedNotificationCenter.xcodeproj
WARN [2020-01-15 23:40:08.78]: Command timed out after 3 seconds on try 1 of 4, trying again with a 6 second timeout...
DEBUG [2020-01-15 23:40:13.30]: Detected derived data path '/Users/cyberbeni/Desktop/framework/TypedNotificationCenter/DerivedData.noindex'

+------------------------------------------------+--------------------------------------------------------------------------------+
|                                                    Summary for scan 2.140.0                                                     |
+------------------------------------------------+--------------------------------------------------------------------------------+
| scheme                                         | TypedNotificationCenter macOS                                                  |
| project                                        | ./TypedNotificationCenter.xcodeproj                                            |
| derived_data_path                              | /Users/cyberbeni/Desktop/framework/TypedNotificationCenter/DerivedData.noindex |
| skip_detect_devices                            | false                                                                          |
| force_quit_simulator                           | false                                                                          |
| reset_simulator                                | false                                                                          |
| disable_slide_to_type                          | true                                                                           |
| reinstall_app                                  | false                                                                          |
| clean                                          | false                                                                          |
| open_report                                    | false                                                                          |
| output_directory                               | ./test_output                                                                  |
| output_types                                   | html,junit                                                                     |
| buildlog_path                                  | ~/Library/Logs/scan                                                            |
| include_simulator_logs                         | false                                                                          |
| should_zip_build_products                      | false                                                                          |
| result_bundle                                  | false                                                                          |
| use_clang_report_name                          | false                                                                          |
| disable_concurrent_testing                     | false                                                                          |
| skip_build                                     | false                                                                          |
| slack_use_webhook_configured_username_and_icon | false                                                                          |
| slack_username                                 | fastlane                                                                       |
| slack_icon_url                                 | https://s3-eu-west-1.amazonaws.com/fastlane.tools/fastlane.png                 |
| skip_slack                                     | false                                                                          |
| slack_only_on_failure                          | false                                                                          |
| xcodebuild_command                             | env NSUnbufferedIO=YES xcodebuild                                              |
| xcode_path                                     | /Applications/Xcode.app                                                        |
+------------------------------------------------+--------------------------------------------------------------------------------+

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `each' for nil

URL: https://api.github.com/search/issues?q=undefined%20method%20%60each%27%20for%20nil+repo:fastlane/fastlane
➡️  [Swift] undefined method `each' for nil:NilClass - Cannot Create Group Within FastlaneSwiftRunner Project
    https://github.com/fastlane/fastlane/issues/15184 [open] 18 💬
    10 hours ago

➡️  undefined method `each' for nil:NilClass
    https://github.com/fastlane/fastlane/issues/15621 [closed] 6 💬
    5 days ago

➡️  fastlane deliver download_metadata crash
    https://github.com/fastlane/fastlane/issues/15806 [open] 6 💬
    3 weeks ago

and 167 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60each%27%20for%20nil&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
Traceback (most recent call last):
	14: from /usr/local/bin/fastlane:23:in `<main>'
	13: from /usr/local/bin/fastlane:23:in `load'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/commands_generator.rb:15:in `start'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/commands_generator.rb:75:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/manager.rb:23:in `work'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:22:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:35:in `test_app': undefined method `each' for nil:NilClass (NoMethodError)
	14: from /usr/local/bin/fastlane:23:in `<main>'
	13: from /usr/local/bin/fastlane:23:in `load'
	12: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/bin/fastlane:23:in `<top (required)>'
	11: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane/lib/fastlane/cli_tools_distributor.rb:111:in `take_off'
	10: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/commands_generator.rb:15:in `start'
	 9: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/commands_generator.rb:75:in `run'
	 8: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	 7: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	 6: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	 5: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	 4: from /Library/Ruby/Gems/2.6.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	 3: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/commands_generator.rb:44:in `block (2 levels) in run'
	 2: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/manager.rb:23:in `work'
	 1: from /Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:22:in `run'
/Library/Ruby/Gems/2.6.0/gems/fastlane-2.140.0/scan/lib/scan/runner.rb:35:in `test_app': [!] undefined method `each' for nil:NilClass (NoMethodError) </pre>
</details>

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.15.2                                                        |
| Ruby                        | 2.6.3                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.21.1 (Apple Git-122.3)                           |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.15.2 (19C57)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib |
| OpenSSL Version             | LibreSSL 2.8.3                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 11.3.1                                                         |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE | en_US.UTF-8 | ✅ |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.140.0 | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.3.0        |
| slack-notifier            | 2.3.2        |
| atomos                    | 0.1.3        |
| claide                    | 1.0.3        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.6        |
| xcodeproj                 | 1.14.0       |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.3.0        |
| terminal-notifier         | 2.0.0        |
| unicode-display_width     | 1.6.0        |
| terminal-table            | 1.8.0        |
| plist                     | 3.5.0        |
| public_suffix             | 2.0.5        |
| addressable               | 2.7.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.7.0        |
| tty-cursor                | 0.7.0        |
| tty-spinner               | 0.9.2        |
| babosa                    | 1.0.3        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.6        |
| excon                     | 0.71.1       |
| faraday                   | 0.17.1       |
| unf_ext                   | 0.0.7.6      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20190701 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.13.1       |
| fastimage                 | 2.1.7        |
| gh_inspector              | 1.1.3        |
| mini_magick               | 4.9.5        |
| multi_xml                 | 0.6.0        |
| rubyzip                   | 1.3.0        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 1.0.0        |
| dotenv                    | 2.7.5        |
| naturally                 | 2.2.0        |
| simctl                    | 1.6.7        |
| jwt                       | 2.1.0        |
| uber                      | 0.1.0        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.2        |
| mini_mime                 | 1.0.2        |
| multi_json                | 1.14.1       |
| signet                    | 0.12.0       |
| memoist                   | 0.16.2       |
| os                        | 1.0.1        |
| googleauth                | 0.10.0       |
| httpclient                | 2.8.3        |
| google-api-client         | 0.36.3       |
| google-cloud-env          | 1.3.0        |
| google-cloud-core         | 1.4.1        |
| digest-crc                | 0.4.1        |
| google-cloud-storage      | 1.25.0       |
| emoji_regex               | 1.0.1        |
| CFPropertyList            | 3.0.2        |
| json                      | 2.3.0        |
| bundler                   | 2.1.4        |
| forwardable               | 1.2.0        |
| logger                    | 1.3.0        |
| stringio                  | 0.0.2        |
| ipaddr                    | 1.2.2        |
| openssl                   | 2.1.2        |
| ostruct                   | 0.1.0        |
| strscan                   | 1.0.0        |
| date                      | 2.0.0        |
| fileutils                 | 1.1.0        |
| etc                       | 1.0.1        |
| io-console                | 0.4.7        |
| zlib                      | 1.0.0        |
| libxml-ruby               | 3.1.0        |
| rexml                     | 3.1.9        |
| psych                     | 3.1.0        |
| mutex_m                   | 0.1.0        |
</details>

*generated on:* **2020-01-15**
</details>

**Comment by proxi** [comment]
As a workaround, adding `disable_slide_to_type: false` helps.

**Comment by Cyberbeni** [comment]
https://github.com/fastlane/fastlane/blob/8de6f50478a1953ddc86f32453cd225d4c29ed23/scan/lib/scan/test_command_generator.rb#L40

This and the next line should be omitted when the target is macOS, or Xcode version is below 10(?), because they don't do anything with the latest Xcode for macOS testing and older Xcodes don't support it and for running UI tests on macOS 10.11-10.13, you need to use older Xcode versions.
