### PR TITLE
[pilot] Fix increase limit for build query

### LINKED ISSUE #21207: distribute breaks when updating from 2.212.1 to 2.212.2 - `undefined method 'size' for Spaceship::ConnectAPI::Platform:Module`
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.212.2`
- Last working version: `2.212.1`

### Regression Description

`distribute` starts failing with error :

```
`distribute': \e[31m[!] undefined method `size' for Spaceship::ConnectAPI::Platform:Module\e[0m (NoMethodError)
```

See also comments in https://github.com/fastlane/fastlane/pull/21087#discussion_r1168682774 

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>
[13:01:20]: Loading from './fastlane/.env.ios'
+---------------------------+---------+---------------------------------------------------------------------------+
|                                                  Used plugins                                                   |
+---------------------------+---------+---------------------------------------------------------------------------+
| Plugin                    | Version | Action                                                                    |
+---------------------------+---------+---------------------------------------------------------------------------+
| fastlane-plugin-appcenter | 1.11.1  | appcenter_fetch_devices, appcenter_fetch_version_number, appcenter_upload |
+---------------------------+---------+---------------------------------------------------------------------------+

[13:01:20]: Sending anonymous analytics information
[13:01:20]: Learn more at https://docs.fastlane.tools/#metrics
[13:01:20]: No personal or sensitive data is sent.
[13:01:20]: You can disable this by adding `opt_out_usage` at the top of your Fastfile
[13:01:20]: -----------------------------
[13:01:20]: --- Step: update_fastlane ---
[13:01:20]: -----------------------------
[13:01:20]: Looking for updates for fastlane...
[13:01:23]: Nothing to update ✅
[13:01:23]: ------------------------------
[13:01:23]: --- Step: default_platform ---
[13:01:23]: ------------------------------
[13:01:23]: Driving the lane 'ios distribute' 🚀
[13:01:23]: ---------------------------------------
[13:01:23]: --- Step: app_store_connect_api_key ---
[13:01:23]: ---------------------------------------
[13:01:23]: --------------------------------------------
[13:01:23]: --- Step: latest_testflight_build_number ---
[13:01:23]: --------------------------------------------
[13:01:23]: Creating authorization token for App Store Connect API
[13:01:24]: Fetching the latest build number for version 6.23.4
[13:01:24]: Latest upload for version 6.23.4 on ios platform is build: 5063951.0
[13:01:24]: ----------------------------------
[13:01:24]: --- Step: upload_to_testflight ---
[13:01:24]: ----------------------------------
[13:01:24]: Creating authorization token for App Store Connect API
[13:01:25]: Waiting for processing on... app_id: XXXXXX, app_version: 6.23.4, build_version: 5063951.0, platform: IOS
[13:01:26]: Successfully finished processing the build 6.23.4 - 5063951.0 for IOS
[13:01:26]: -------------------
[13:01:26]: --- Step: is_ci ---
[13:01:26]: -------------------
[13:01:26]: -------------------
[13:01:26]: --- Step: slack ---
[13:01:26]: -------------------
[13:01:26]: Successfully sent Slack notification
[13:01:26]: An error occurred while executing the `error` block:
[13:01:26]: undefined method `size' for Spaceship::ConnectAPI::Platform:Module
+--------------------------------+----------------+
|                  Lane Context                   |
+--------------------------------+----------------+
| ENVIRONMENT                    | ios            |
| DEFAULT_PLATFORM               | ios            |
| PLATFORM_NAME                  | ios            |
| LANE_NAME                      | ios distribute |
| LATEST_TESTFLIGHT_BUILD_NUMBER | 5063951.0      |
| LATEST_TESTFLIGHT_VERSION      | 6.23.4         |
+--------------------------------+----------------+

+------+--------------------------------+-------------+
|                  fastlane summary                   |
+------+--------------------------------+-------------+
| Step | Action                         | Time (in s) |
+------+--------------------------------+-------------+
| 1    | update_fastlane                | 2           |
| 2    | default_platform               | 0           |
| 3    | app_store_connect_api_key      | 0           |
| 4    | latest_testflight_build_number | 1           |
| 💥   | upload_to_testflight           | 1           |
| 6    | is_ci                          | 0           |
| 7    | slack                          | 0           |
+------+--------------------------------+-------------+

+-----------+--------------+----------------+
|         Plugin updates available          |
+-----------+--------------+----------------+
| Plugin    | Your Version | Latest Version |
+-----------+--------------+----------------+
| appcenter | 1.11.1       | 2.1.0          |
+-----------+--------------+----------------+
[13:01:26]: To update all plugins, just run
[13:01:26]: $ bundle exec fastlane update_plugins

[13:01:26]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
bundler: failed to load command: fastlane (/Users/builder/.rbenv/versions/3.0.4/bin/fastlane)
/Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/pilot/lib/pilot/build_manager.rb:160:in `distribute': \e[31m[!] undefined method `size' for Spaceship::ConnectAPI::Platform:Module\e[0m (NoMethodError)
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/upload_to_testflight.rb:32:in `run'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:263:in `block (2 levels) in execute_action'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/actions/actions_helper.rb:69:in `execute_action'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:255:in `block in execute_action'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `chdir'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:229:in `execute_action'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/fast_file.rb:159:in `method_missing'
	from Fastfile:173:in `distribute_testflight'
	from Fastfile:15:in `block (2 levels) in parsing_binding'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/lane_manager.rb:47:in `cruise_lane'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:110:in `block (2 levels) in run'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:187:in `call'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/command.rb:157:in `run'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/runner.rb:444:in `run_active_command'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:124:in `run!'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/commander-4.6.0/lib/commander/delegates.rb:18:in `run!'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:354:in `run'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/commands_generator.rb:43:in `start'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/fastlane/lib/fastlane/cli_tools_distributor.rb:123:in `take_off'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/fastlane-2.212.2/bin/fastlane:23:in `<top (required)>'
	from /Users/builder/.rbenv/versions/3.0.4/bin/fastlane:25:in `load'
	from /Users/builder/.rbenv/versions/3.0.4/bin/fastlane:25:in `<top (required)>'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:58:in `load'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:58:in `kernel_load'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:23:in `run'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:492:in `exec'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:34:in `dispatch'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:28:in `start'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.8/exe/bundle:45:in `block in <top (required)>'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
	from /Users/builder/.rbenv/versions/3.0.4/lib/ruby/gems/3.0.0/gems/bundler-2.4.8/exe/bundle:33:in `<top (required)>'
	from /Users/builder/.rbenv/versions/3.0.4/bin/bundle:25:in `load'
	from /Users/builder/.rbenv/versions/3.0.4/bin/bundle:25:in `<main>'

</pre>
</details>

### PR DESCRIPTION
**Pull request by eric**
### Checklist
- [ ] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [ ] I see several green `ci/circleci` builds in the "All checks have passed" section of my PR ([connect CircleCI to GitHub](https://support.circleci.com/hc/en-us/articles/360008097173-Why-aren-t-pull-requests-triggering-jobs-on-my-organization-) if not)
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [ ] I've updated the documentation if necessary.

### Motivation and Context
Resolves #21207

### Description
There was an issue with #21087

### CODE REVIEW

File: pilot/lib/pilot/build_manager.rb [hunk 1]
```diff
@@ -157,7 +157,7 @@ def distribute(options, build: nil)
           end
         end
         platform = Spaceship::ConnectAPI::Platform.map(fetch_app_platform)
-        build ||= Spaceship::ConnectAPI::Build.all(app_id: app.id, version: app_version, build_number: build_number, sort: "-uploadedDate", platform: platform, limit: Spaceship::ConnectAPI::Platform.size).first
+        build ||= Spaceship::ConnectAPI::Build.all(app_id: app.id, version: app_version, build_number: build_number, sort: "-uploadedDate", platform: platform, limit: Spaceship::ConnectAPI::Platform::ALL.size).first
```
Comment (ainame) [inline pilot/lib/pilot/build_manager.rb:160]: 🚀 
 https://github.com/fastlane/fastlane/blob/08e50939de32aa411e1dc2d113aae8247b324dc2/spaceship/lib/spaceship/connect_api.rb#L89

**Review by ainame — APPROVED** [review]
This PR fixes https://github.com/fastlane/fastlane/issues/21207
Thank you for the follow-up!
