### PR TITLE
Fixed recent spaceship change to work on Ruby 2.0 too

### LINKED ISSUE #8955: fast lane Pilot: undefined method `local_variable_get'  error
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
**undefined method `local_variable_get'  when running Pilot**
Mobile iOS app uploads correctly to iTuneConnect and start TestFlight however the "Fastlane distribute" command fails with error before terminating. 

Fastlane distribute
[09:46:18]: Seems like launching fastlane takes a while - please run
[09:46:18]: 
[09:46:18]: $ [sudo] gem cleanup
[09:46:18]: 
[09:46:18]: to uninstall outdated gems and make fastlane launch faster
[09:46:18]: Alternatively it's recommended to start using a Gemfile to lock your dependencies
[09:46:18]: To get started with a Gemfile, run
[09:46:18]: 
[09:46:18]: $ bundle init
[09:46:18]: $ echo 'gem "fastlane"' >> Gemfile
[09:46:18]: $ bundle install
[09:46:18]: 
[09:46:18]: After creating the Gemfile and Gemfile.lock, commit those files into version control
[09:46:18]: For more information, check out https://guides.cocoapods.org/using/a-gemfile.html
[09:46:21]: -------------------------------------------------
[09:46:21]: --- Step: Verifying required fastlane version ---
[09:46:21]: -------------------------------------------------
[09:46:21]: Your fastlane version 2.28.2 matches the minimum requirement of 1.105.0  ✅
[09:46:21]: ------------------------------
[09:46:21]: --- Step: default_platform ---
[09:46:21]: ------------------------------
[09:46:21]: Driving the lane 'ios distribute' 🚀
[09:46:21]: -------------------
[09:46:21]: --- Step: pilot ---
[09:46:21]: -------------------
[09:46:21]: Login to iTunes Connect (commercial-mobilecoe@cardinalhealth.com)
[09:46:27]: Login successful
[09:46:28]: Ready to upload new build to TestFlight (App: 1217881094)...
[09:46:43]: Going to upload updated app to iTunes Connect
[09:46:43]: This might take a few minutes. Please don't interrupt the script.
[09:49:41]: iTunes Transporter successfully finished its job
[09:49:43]: -----------------------------------------------------------------------------------------------------
[09:49:43]: Successfully uploaded package to iTunes Connect. It might take a few minutes until it's visible online.
[09:49:43]: -----------------------------------------------------------------------------------------------------
[09:49:43]: Successfully uploaded the new binary to iTunes Connect
[09:49:43]: If you want to skip waiting for the processing to be finished, use the `skip_waiting_for_build_processing` option
+------------------+----------------+
|           Lane Context            |
+------------------+----------------+
| DEFAULT_PLATFORM | ios            |
| PLATFORM_NAME    | ios            |
| LANE_NAME        | ios distribute |
+------------------+----------------+
[09:49:43]: undefined method `local_variable_get' for #<Binding:0x007fc68cc803e8>

+------+------------------------------+-------------+
|                 fastlane summary                  |
+------+------------------------------+-------------+
| Step | Action                       | Time (in s) |
+------+------------------------------+-------------+
| 1    | Verifying required fastlane  | 0           |
|      | version                      |             |
| 2    | default_platform             | 0           |
| 💥    | pilot                        | 202         |
+------+------------------------------+-------------+

[09:49:44]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...

Found no similar issues. To create a new issue, please visit:
https://github.com/fastlane/fastlane/issues/new
Run `fastlane env` to append the fastlane environment to your issue
/Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/client.rb:133:in `block in assert_required_params': [!] undefined method `local_variable_get' for #<Binding:0x007fc68cc803e8> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/client.rb:132:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/client.rb:132:in `assert_required_params'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/client.rb:9:in `get_build_trains'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/build_trains.rb:13:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/build.rb:83:in `all'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/spaceship/lib/spaceship/test_flight/build.rb:94:in `all_processing_builds'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane_core/lib/fastlane_core/build_watcher.rb:6:in `wait_for_build_processing_to_be_complete'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/pilot/lib/pilot/build_manager.rb:38:in `upload'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/actions/pilot.rb:15:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:252:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:230:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:226:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:226:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/fast_file.rb:146:in `method_missing'
	from Fastfile:52:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/lane_manager.rb:52:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/commands_generator.rb:104:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:40:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-fastlane-4.4.4/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/commands_generator.rb:303:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/fastlane/lib/fastlane/cli_tools_distributor.rb:66:in `take_off'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-2.28.2/bin/fastlane:20:in `<top (required)>'
	from /usr/local/bin/Fastlane:22:in `load'
	from /usr/local/bin/Fastlane:22:in `<main>'

### Environment

Please run `fastlane env` and copy the output below. This will help us help you :+1:
If you used `--capture_output` option please remove this block - as it is already included there.

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.11.6                                                        |
| Ruby                        | 2.0.0                                                          |
| Bundler?                    | false                                                          |
| Git                         | git version 2.9.3 (Apple Git-75)                               |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.11.6 (15G1004)                                     |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib |
| OpenSSL Version             | OpenSSL 0.9.8zc 19 Mar 2015                                    |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 8.1                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.105.0"

default_platform :ios

platform :ios do
  before_all do
    # ENV["SLACK_URL"] = "https://hooks.slack.com/services/..."
    #cocoapods
    
  end

  desc "Runs all the tests"
  lane :test do
    scan
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    # match(type: "appstore") # more information: https://codesigning.guide
    gym(scheme: "OrderExpress-Build") # Build your app - more options available
    pilot

    # sh "your_script.sh"
    # You can also use other beta testing services here (run `fastlane actions`)
  end

  desc "Deploy a new version to the App Store"
  lane :release do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "OrderExpress-Build") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  desc"Distribute via fastlane Pilot"
  lane :distribute do
  pilot(
    username: ENV["ITUNES_CONNECT_USER"],
    wait_processing_interval: 30,
    distribute_external: false, #internal user only
    skip_submission: false, #do not notify the testersy
    ipa: "signed.ipa"  #path of the ipa generated by your build script
  )
  end

  # You can define as many lanes as you want

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    # slack(
    #   message: "Successfully deployed new App Update."
    # )
  end

  error do |lane, exception|
    # slack(
    #   message: exception.message,
    #   success: false
    # )
  end
end


# More information about multiple platforms in fastlane: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Platforms.md
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md

# fastlane reports which actions are used
# No personal data is recorded. Learn more at https://github.com/fastlane/enhancer
```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier "com.xxxxxxxx.xxxxxx" # The bundle identifier of your app
apple_id "xxxxx@xxxxx.com" # Your Apple email address

team_id "XXXXXXXX"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md
```
</details>

### fastlane gems

| Gem      | Version | Update-Status  |
| -------- | ------- | -------------- |
| fastlane | 2.28.2  | 💥 Check failed |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| slack-notifier            | 1.5.1        |
| claide                    | 1.0.1        |
| colored2                  | 3.1.2        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.4.4        |
| rouge                     | 1.11.1       |
| xcpretty                  | 0.2.4        |
| terminal-notifier         | 1.6.3        |
| terminal-table            | 1.4.5        |
| plist                     | 3.1.0        |
| multipart-post            | 2.0.0        |
| word_wrap                 | 1.0.0        |
| tty-screen                | 0.5.0        |
| babosa                    | 1.0.2        |
| colored                   | 1.2          |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.4        |
| excon                     | 0.53.0       |
| faraday                   | 0.9.2        |
| unf_ext                   | 0.0.7.2      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20160826 |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| gh_inspector              | 1.0.2        |
| uber                      | 0.0.15       |
| representable             | 2.3.0        |
| retriable                 | 2.1.0        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| hurley                    | 0.2          |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.1.0        |
| jwt                       | 1.5.6        |
| memoist                   | 0.15.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.1        |
| httpclient                | 2.8.2.4      |
| google-api-client         | 0.9.15       |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.5.5        |
| rubyzip                   | 1.1.7        |
| security                  | 0.1.3        |
| xcpretty-travis-formatter | 0.0.4        |
| dotenv                    | 2.1.1        |
| bundler                   | 1.12.0       |
| faraday_middleware        | 0.10.0       |
| json                      | 1.8.3        |
| addressable               | 2.3.8        |
| fastimage                 | 1.9.0        |
</details>

*generated on:* **2017-04-21**
</details>

### PR DESCRIPTION
**Pull request by snatchev**
Fixes #8955

### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
Could you update the PR title to be easier to understand for users? Something like `Fixed recent spaceship change to work on Ruby 2.0 too`

**Review by hjanuschka — APPROVED** [review]
⭐️
