### ISSUE TITLE
Produce failing to create app in iTunesConnect

### ISSUE THREAD

**Issue by trustyfrog** [fastlane/fastlane#5728]
### New Issue Checklist

- [X] Updated fastlane to the latest version
- [X] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

I've been running an automated app deployment process for a while now. (20, or so apps over several weeks). It follows the the process of:

```
produce(
  team_id: team_id,
  username: username,
  app_identifier: app_identifier,
  app_name: app_name,
  sku: app_identifier,
  app_version: app_version,
  language: language)
        
match(
  team_id: team_id,
  git_url: git_url,
  git_branch: git_branch,
  type: "development",
  username: username,
  app_identifier: app_identifier,
  readonly: false)

match(
  team_id: team_id,
  git_url: git_url,
  git_branch: git_branch,
  type: "appstore",
  username: username,
  app_identifier: app_identifier,
  readonly: false)
```

Just recently (earlier this week) _produce_ has started failing with app creation on iTunes Connect. The app is successfully made in Developer but there's no sign of it in iTunes Connect (with one exception)

If I run this a second time I get the error "The App Name you entered has already been used. The SKU number you entered has already been used."

If I had to speculate, it's like the app has been created in iTunes Connect but is not visible in the UI and it is an in-between state.

I was playing around with this for a bit, and sometime after manually running match (for appstore) the iTunes Connect app I originally requested just appeared (proving that the app name was originally valid).

I have also tried this with more random names that are unlikely to exist, just in case.

I noticed this starting to happen earlier this week. I have updated all gems to latest version.

##### Complete output when running fastlane, including the stack trace and command used

```
+----------------+----------------------------+
|          [32mSummary for produce 1.2.0[0m          |
+----------------+----------------------------+
| team_id        | xxx                 |
| username       | ios-dev@xxx.com        |
| app_identifier | xxx |
| app_name       | xxx           |
| sku            | xxx |
| app_version    | 1.0                        |
| language       | English                    |
| skip_itc       | false                      |
| skip_devcenter | false                      |
+----------------+----------------------------+

[14:03:11]: Creating new app 'xxx' on the Apple Dev Center
[14:03:12]: Created app xxx
[14:03:13]: [32mFinished creating new app 'xxx' on the Dev Center[0m
[14:03:17]: [32mCreating new app 'xxx' on iTunes Connect[0m
[14:03:21]: Waiting for the newly created application to be available on iTunes Connect...```
<<Repeats>>

### Environment

fastlane 1.100.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? NO
Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? NO

**Comment by KrauseFx** [comment]
Was this issue resolved?

**Comment by iPavel92** [comment]
I'm having the same problem right now
Seems like I've catch the bug https://github.com/fastlane/fastlane/issues/4797
After that I've updated produce. Now I'm having 3 apps in this state:
- App ID is created in Dev Center.
- App ID cannot be deleted because of "An unspecified error occurred.
The App ID '8Q273L2PVC.com.xxxx' appears to be in use by the App Store, so it can not be removed at this time."
- App is not visible in iTunesConnect
- App cannot be created in iTunesConnect manually (the App ID is not visible in combobox)
- Produce fails with the output:
```
[DevCenter] App 'com.xxxx' already exists, nothing to do on the Dev Center
Creating new app 'com.xxxx' on iTunes Connect
Looking for related GitHub issues on fastlane/fastlane...
Error finding relevant GitHub issues: undefined method `map' for nil:NilClass
[!] The request could not be completed because:
The App Name you entered has already been used. The SKU number you entered has already been used. The SKU number you entered has already been used. The App Name you entered has already been used. Your app information could not be saved. The information for at least one field is missing or is in the wrong format.
```

Any advise how to fix apps after https://github.com/fastlane/fastlane/issues/4797 ?

**Comment by iPavel92** [comment]
After about 24 hours apps became visible in iTC. Seems like everythinп is OK after updating to new produce 👍

**Comment by TKBurner** [comment]
@iPavel92 Thanks for letting me know! Glad to hear you are up and running. 👍

**Comment by trustyfrog** [comment]
Same here; apps turned up some time later.

**Comment by TKBurner** [comment]
@trustyfrog Awesome! Glad to hear you are up and running! 👍

**Comment by CareerFairPlus** [comment]
I ran into this problem as well just now after updating spaceship to 0.31.10.  My app is not visible on iTC but when running produce, I get the following error message:
```
[!] The request could not be completed because:
	The App Name you entered has already been used. The App Name you entered has already been used.
```

**Comment by trustyfrog** [comment]
I've seen this resolve itself anywhere between one and three days. I don't know why, but it seems that it gets into a pending state where it exists but is not visible, but only via the API.

**Comment by CareerFairPlus** [comment]
@trustyfrog Thanks for the heads up.  I hate iTC!

**Comment by TKBurner** [comment]
@CareerFairPlus Did the app show up eventually? thanks!

**Comment by lupugabriel** [comment]
Hi there. i have a solution for this. After you create the app in terminal. Just upload a build and the app will appear.

Basically i do these steps:
1. run from terminal to create the app.
2. upload a first build from xCode
3. the app will appear on ItunesConnect once the build is uploaded.
4. app = Spaceship::Tunes::Application.find("com.*****") it will work.
