### PR TITLE
[scan] fix crash on TestResultParser when disable_xcpretty=true

### LINKED ISSUE #16480: [scan] undefined method `scan' for nil:NilClass
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.147.0`
- Last working version: `2.146.1`

### Regression Description

Introduced by https://github.com/fastlane/fastlane/pull/16375 when using `scan` with `only_testing` and `disable_xcpretty`.

##### Complete output when running fastlane, including the stack trace and command used

<details>
  <pre>NoMethodError: [!] undefined method `scan' for nil:NilClass
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/scan/lib/scan/test_result_parser.rb:7:in `parse_result'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/scan/lib/scan/runner.rb:90:in `handle_results'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/scan/lib/scan/runner.rb:22:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/scan/lib/scan/manager.rb:23:in `work'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/actions/run_tests.rb:16:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:261:in `block (2 levels) in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:253:in `block in execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:73:in `run'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server_action_command_executor.rb:42:in `execute'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:181:in `execute_action_command'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:176:in `process_action_command'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:123:in `handle_action_command'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:86:in `parse_and_execute_command'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:62:in `block in receive_and_process_commands'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `loop'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:49:in `receive_and_process_commands'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:158:in `listen'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/server/socket_server.rb:38:in `start'
  /Users/vagrant/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/fastlane-2.148.0/fastlane/lib/fastlane/swift_lane_manager.rb:223:in `block in start_socket_thread'</pre>
</details>

### PR DESCRIPTION
**Pull request by gobetti**
### Checklist
- [x] I've run `bundle exec rspec` from the root directory to see all new and existing tests pass
- [x] I've followed the _fastlane_ code style and run `bundle exec rubocop -a` to ensure the code style is valid
- [x] I've read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I've updated the documentation if necessary.

### Motivation and Context
Fixes #16480

### Description
`test_results` used to early return when `disable_xcpretty` is true, but that would lead into a crash inside `handle_test_results` (the only method that calls `test_results`) because it doesn't check for nil. I'm changing the early return to be in `handle_test_results` instead so the whole thing is skipped.

### Testing Steps
I believe any combination of `disable_xcpretty: true` without `fail_build: false` would lead into the crash before this fix. I used to have `fail_build: true` so I had never detected it myself.

### CODE REVIEW

**Review by joshdholtz — APPROVED** [review]
This makes a lot of sense! And even goes with what the `disable_xcpretty` option says it does 😊 Really appreciate the contribution ❤️

**Comment by 1oo7** [comment]
How would this crash manifest?
