### ISSUE TITLE
undefined method `[]' for #<Spaceship::ConnectAPI::PreReleaseVersion:0x00007fb398a54670> (NoMethodError)

### ISSUE THREAD

**Issue by agordeev** [fastlane/fastlane#14845]
### New Regression Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Regression Information

- Breaking version: `2.125.0`
- Last working version: not sure

### Regression Description

`latest_testflight_build_number` has stopped working. Throws this:

```
/Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:47:in `get_build_number': [!] undefined method `[]' for #<Spaceship::ConnectAPI::PreReleaseVersion:0x00007fb398a54670> (NoMethodError)
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:11:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/latest_testflight_build_number.rb:11:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:256:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:235:in `block in execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:157:in `trigger_action_by_name'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/fast_file.rb:154:in `method_missing'
	from Fastfile:49:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane.rb:33:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/runner.rb:476:in `run_active_command'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:76:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/commander-fastlane-4.4.6/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:333:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/commands_generator.rb:41:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/fastlane/lib/fastlane/cli_tools_distributor.rb:119:in `take_off'
	from /Library/Ruby/Gems/2.3.0/gems/fastlane-2.125.0/bin/fastlane:23:in `<top (required)>'
	from /usr/local/bin/fastlane:22:in `load'
	from /usr/local/bin/fastlane:22:in `<main>'
Exited with code 1
```

**Comment by jcharr1** [comment]
You must have created this issue while I was in the process of posting about the exact same thing. Can a mod maybe merge my duplicate I made over here? https://github.com/fastlane/fastlane/issues/14846

**Comment by tharak** [comment]
same problem with `app_store_build_number(live: false)`

`/fastlane-2.125.0/fastlane/lib/fastlane/actions/app_store_build_number.rb:47:in `get_build_number': [!] undefined method `[]' for #<Spaceship::ConnectAPI::PreReleaseVersion:0x007fa797d649a8> (NoMethodError)`

**Comment by jcharr1** [comment]
Btw, @agordeev it still works in 2.124.0, so you can downgrade to that version as a workaround for now if you want.

**Comment by joshdholtz** [comment]
On it! Fix coming out this morning

**Comment by joshdholtz** [comment]
Fix is here ^ Will merge and release right away after its reviewed 💪

Sorry about this 😔 Merged a massive change to how the new `Spaceship::ConnectAPI` module was implemented for interacting with the App Store Connect API and this was missed (https://github.com/fastlane/fastlane/pull/14839). This action was the only thing outside of _pilot_ using this 😱

**Comment by joshdholtz** [comment]
Hey all! Fix for this was just released in `2.125.1` 😇 Happy fastlaning 🚀 ❤️

**Comment by helloniklas** [comment]
@joshdholtz So I'm passed the previous error with version 2.125.1, but it now seems to increment the version number rather than the build number? Not sure if I'm doing something else wrong as I'm just trying this out for the first time.

I have

```
        increment_build_number(
            build_number: latest_testflight_build_number + 1,
            xcodeproj: "MyProject.xcodeproj"
        )

**Comment by d-a-n** [comment]
@joshdholtz Thanks for the fix. The exception is gone however now it always returns 1.

```
[17:08:52]: Login to App Store Connect (****)
[17:08:53]: Login successful
[17:08:54]: Using initial build number of 1 for version 
```

It was working fine with version "2.124.0".

**Comment by helloniklas** [comment]
@joshdholtz it also asked me to set the current project version in the building setting...

**Comment by joshdholtz** [comment]
@helloniklas Can you puts a `puts "build_number: #{latest_testflight_build_number}"` in your fastfile to see what that is returning? I don't understand how the version would be incremented 🤔

@d-a-n Can you paste your whole output and any options you are using with `latest_testflight_build_number`?

**Comment by joshdholtz** [comment]
Also, are you all manually passing in a `version` option into `latest_testflight_build_number`? Or are you using `live: true`?

**Comment by helloniklas** [comment]
@joshdholtz apologies I read it wrong, my version was 1 and build number 118, it said it upped it from 1 to 2, but as @d-a-n pointed out, it never get the build 118 but set it to 1...

**Comment by helloniklas** [comment]
@joshdholtz I'm not passing version number into latest_testflight_build_number... Is that needed?

**Comment by joshdholtz** [comment]
Ahhh, I think I see what might be going on 🤔 Going to make some more changes!

**Comment by d-a-n** [comment]
@joshdholtz As soon as I pass in the version to `latest_testflight_build_number` it is working.

**Comment by joshdholtz** [comment]
@d-a-n Thanks for confirming that! Got a fix in the works right now for when version isn't passed 🙃

**Comment by d-a-n** [comment]
@joshdholtz You are AWESOME! Thanks so much!

**Comment by joshdholtz** [comment]
^ This is released in `2.125.2` 🚀 Hopefully we are good now 🤞 ❤️
