### PR TITLE
Handle old Swift FastlaneRunner commands

### LINKED ISSUE #11468: [Regression] undefined method `to_sym' since updating to 2.74.0
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

After updating to 2.74.0 from 2.73.0, I can no longer run fastlane, as it exits with the error "undefined method to_sym for nil:NilClass. See output below:

##### Complete output when running fastlane, including the stack trace and command used

```
$ bundle exec fastlane release --env app --verbose
[✔] 🚀 
DEBUG [2018-01-08 14:26:20.47]: Checking if there are any plugins that should be loaded...
INFO [2018-01-08 14:26:20.65]: Loading from './fastlane/.env.app'
DEBUG [2018-01-08 14:26:20.65]: Checking for new user-provided tool configuration files
INFO [2018-01-08 14:26:20.73]: FastlaneSwiftRunner project is up-to-date
DEBUG [2018-01-08 14:26:20.74]: Waiting for 5 seconds for a connection from FastlaneRunner
INFO [2018-01-08 14:26:20.99]: $ ./fastlane/FastlaneRunner lane release logMode verbose > /dev/null
DEBUG [2018-01-08 14:26:21.01]: Client connected
WARN [2018-01-08 14:26:21.01]: Lane Context:
INFO [2018-01-08 14:26:21.01]: {:ENVIRONMENT=>"app"}
ERROR [2018-01-08 14:26:21.02]: undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
ERROR [2018-01-08 14:26:21.02]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `to_sym' for nil
Did you mean?  to_s

URL: https://api.github.com/search/issues?q=undefined%20method%20%60to_sym'%20for%20nil%0ADid%20you%20mean?%20%20to_s+repo:fastlane/fastlane
➡️  undefined method `to_sym' for nil:NilClass when running gym
    https://github.com/fastlane/fastlane/issues/10717 [closed] 11 💬
    a week ago

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (/usr/local/bin/fastlane)
NoMethodError: [!] undefined method `to_sym' for nil:NilClass
Did you mean?  to_s
Did you mean?  to_s
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/command_parser.rb:9:in `parse'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/socket_server.rb:79:in `parse_and_execute_command'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/socket_server.rb:60:in `block in receive_and_process_commands'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/socket_server.rb:47:in `loop'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/socket_server.rb:47:in `receive_and_process_commands'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/socket_server.rb:156:in `listen'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/server/socket_server.rb:36:in `start'
  /Library/Ruby/Gems/2.3.0/gems/fastlane-2.74.0/fastlane/lib/fastlane/swift_lane_manager.rb:205:in `block in start_socket_thread'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                          |
| --------------------------- | -------------------------------------------------------------- |
| OS                          | 10.13.2                                                        |
| Ruby                        | 2.3.3                                                          |
| Bundler?                    | true                                                           |
| Git                         | git version 2.14.3 (Apple Git-98)                              |
| Installation Source         | /usr/local/bin/fastlane                                        |
| Host                        | Mac OS X 10.13.2 (17C88)                                       |
| Ruby Lib Dir                | /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib |
| OpenSSL Version             | LibreSSL 2.2.7                                                 |
| Is contained                | false                                                          |
| Is homebrew                 | false                                                          |
| Is installed via Fabric.app | false                                                          |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                    |
| Xcode Version               | 9.2                                                            |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_GB.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile.swift`</summary>

```ruby
// Customize this file, documentation can be found here:
// https://docs.fastlane.tools/
// All available actions: https://docs.fastlane.tools/actions
// can also be listed using the `fastlane actions` command

// Change the syntax highlighting to Swift
// All lines starting with // are ignored when running `fastlane`

// If you want to automatically update fastlane if a new version is available:
// updateFastlane()

import Foundation

class Fastfile: LaneFile {
    // This is the minimum version number required.
    // Update this, if you use features of a newer version
    var fastlaneVersion: String { return "2.70.0" }

    func beforeAll() {
        // environmentVariables["SLACK_URL"] = "https://hooks.slack.com/services/..."
        cocoapods()
        // carthage()
    }

    func testLane() {
        desc("Runs all the tests")
        runTests()
    }

    func betaLane() {
        desc("Submit a new Beta Build to Apple TestFlight. This will also make sure the profile is up to date")

        // syncCodeSigning(gitUrl: "gitUrl", appIdentifier: [appIdentifier], username: appleID)
        let changelog = prompt(text: "Changelog: ")
        incrementBuildNumber()
        buildApp(scheme: ProcessInfo.processInfo.environment["APP_SCHEME"], clean: true) // more options available
        uploadToTestflight(username: appleID, changelog: changelog)
        // You can also use other beta testing services here (run `fastlane actions`)
    }

    func releaseLane() {
        desc("Deploy a new version to the App Store")

        // syncCodeSigning(gitUrl: "gitUrl", type: "appstore", appIdentifier: [appIdentifier], username: appleID)
        if ProcessInfo.processInfo.environment["APP_SCHEME"] == "PowerMusic" {
            captureScreenshots(devices: ["iPad Pro (12.9-inch)", "iPad Pro (9.7-inch)", "iPad Pro (10.5-inch)"], languages: ["en-GB"], launchArguments: ["-screenshots"], outputDirectory: "screenshots/PowerMusic", scheme: "PowerMusicUITests")
            //frameScreenshots(white: "true", path: "screenshots/PowerMusic")
        } else {
            captureScreenshots(devices: ["iPhone 4s", "iPhone SE", "iPhone 8", "iPhone 8 Plus", "iPhone X", "iPad Pro (12.9-inch)", "iPad Pro (9.7-inch)", "iPad Pro (10.5-inch)"], languages: ["en-GB"], launchArguments: ["-screenshots"], outputDirectory: "screenshots/PowerMusicReader", scheme: "PowerMusicReaderUITests")
            //frameScreenshots(white: "true", path: "screenshots/PowerMusicReader")
        }
        incrementBuildNumber()
        buildApp(scheme: ProcessInfo.processInfo.environment["APP_SCHEME"], clean: true) // more options available
        uploadToAppStore(username: appleID, app: appIdentifier, force: false)
        // frameScreenshots()
    }

    // You can define as many lanes as you want

    func afterAll(currentLane: String) {
        // This block is called, only if the executed lane was successful
        // slack(
        //     message: "Successfully deployed new App Update.",
        //     slackUrl: "slackURL"
        // )
    }

    func onError(currentLane: String, errorInfo: String) {
        // slack(
        //     message: errorInfo,
        //     slackUrl: "slackUrl",
        //     success: false
        // )
    }

    // All available actions: https://docs.fastlane.tools/actions

    // fastlane reports which actions are used. No personal data is recorded.
    // Learn more at https://github.com/fastlane/fastlane/#metrics
}

```
</details>

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.74.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.16.0       |
| io-console                | 0.4.5        |
| CFPropertyList            | 2.3.6        |
| concurrent-ruby           | 1.0.5        |
| i18n                      | 0.9.1        |
| minitest                  | 5.10.3       |
| thread_safe               | 0.3.6        |
| tzinfo                    | 1.2.4        |
| activesupport             | 4.2.10       |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.2        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| fuzzy_match               | 2.0.4        |
| nap                       | 1.1.0        |
| cocoapods-core            | 1.3.1        |
| cocoapods-deintegrate     | 1.0.1        |
| cocoapods-downloader      | 1.1.3        |
| cocoapods-plugins         | 1.0.0        |
| cocoapods-search          | 1.0.0        |
| cocoapods-stats           | 1.0.0        |
| netrc                     | 0.11.0       |
| cocoapods-trunk           | 1.3.0        |
| cocoapods-try             | 1.1.0        |
| colored2                  | 3.1.2        |
| escape                    | 0.0.4        |
| fourflusher               | 2.0.1        |
| gh_inspector              | 1.0.3        |
| molinillo                 | 0.5.7        |
| ruby-macho                | 1.1.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.4        |
| cocoapods                 | 1.3.1        |
| colored                   | 1.2          |
| highline                  | 1.7.10       |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.10       |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.60.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.13.1       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.1        |
| jwt                       | 2.1.0        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.2       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.8.1        |
| googleauth                | 0.6.2        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.13.6       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.4.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.6.4        |
| tty-cursor                | 0.5.0        |
| tty-spinner               | 0.7.0        |
| word_wrap                 | 1.0.0        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 1.0.0        |
</details>

*generated on:* **2018-01-08**
</details>

### PR DESCRIPTION
**Pull request by taquitos**
The new client/server communication model breaks the old way of doing things. 
Since we don't have a mechanism for updating old `FastlaneRunner` projects yet, we need to handle old command styles
Fixes #11468

### CODE REVIEW

**Review by KrauseFx — APPROVED** [review]
🎷

**Comment by taquitos** [comment]
@KrauseFx I need to do some testing real quick before I merge, but need https://github.com/fastlane/fastlane/pull/11476 merged before then 🙃

**Comment by taquitos** [comment]
Testing finished

**Comment by KrauseFx** [comment]
Best testing 👍
