### ISSUE TITLE
Scan completion issue: undefined method `username=' for Slack::Notifier

### ISSUE THREAD

**Issue by MaximusMcCann** [fastlane/fastlane#11590]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description
ERROR [2018-01-16 12:20:45.54]: undefined method `username=' for #<Slack::Notifier:0x00007f89c0179b38>

<details><summary>Details</summary>
##### Complete output when running fastlane, including the stack trace and command used
ERROR [2018-01-16 12:20:45.54]: undefined method `username=' for #<Slack::Notifier:0x00007f89c0179b38>
INFO [2018-01-16 12:20:45.54]: Successfully generated documentation at path '/Users/distiller/ios/fastlane/README.md'

+------+--------------------------+-------------+
|               fastlane summary                |
+------+--------------------------+-------------+
| Step | Action                   | Time (in s) |
+------+--------------------------+-------------+
| 1    | update_fastlane          | 2           |
| 2    | default_platform         | 0           |
| 3    | git_branch               | 0           |
| 4    | Switch to uiTestDev lane | 0           |
| 💥   | scan                     | 973         |
+------+--------------------------+-------------+

DEBUG [2018-01-16 12:20:45.55]: All plugins are up to date
ERROR [2018-01-16 12:20:45.55]: fastlane finished with errors

Looking for related GitHub issues on fastlane/fastlane...
Search query: undefined method `username=' for Slack::Notifier

URL: https://api.github.com/search/issues?q=undefined%20method%20%60username='%20for%20Slack::Notifier+repo:fastlane/fastlane
➡️  [!] undefined method `fetch' for #<String:0x007fb9844e32d0> (NoMethodError)
    https://github.com/fastlane/fastlane/issues/10967 [open] 3 💬
    2 days ago

➡️  [Regression] undefined method `to_sym' since updating to 2.74.0
    https://github.com/fastlane/fastlane/issues/11468 [closed] 12 💬
    a week ago

➡️  undefined method `[]' for nil:NilClass during Match
    https://github.com/fastlane/fastlane/issues/10960 [closed] 19 💬
    21 Nov 2017

and 50 more at: https://github.com/fastlane/fastlane/search?q=undefined%20method%20%60username=%27%20for%20Slack::Notifier&type=Issues&utf8=✓

🔗  You can ⌘ + double-click on links to open them directly in your browser.
DEBUG [2018-01-16 12:20:46.15]: All plugins are up to date
bundler: failed to load command: fastlane (/Users/distiller/.gem/ruby/2.4.2/bin/fastlane)
NoMethodError: [!] undefined method `username=' for #<Slack::Notifier:0x00007f89c0179b38>
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/scan/lib/scan/slack_poster.rb:12:in `run'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/scan/lib/scan/runner.rb:64:in `handle_results'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/scan/lib/scan/runner.rb:23:in `run'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/scan/lib/scan/manager.rb:18:in `work'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/actions/run_tests.rb:22:in `run'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:253:in `block (2 levels) in execute_action'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/actions/actions_helper.rb:50:in `execute_action'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:231:in `block in execute_action'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:227:in `chdir'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:227:in `execute_action'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:148:in `trigger_action_by_name'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:43:in `block in parsing_binding'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:201:in `try_switch_to_lane'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:156:in `trigger_action_by_name'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/fast_file.rb:148:in `method_missing'
  Fastfile:37:in `block in parsing_binding'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/lane.rb:33:in `call'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:49:in `block in execute'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:45:in `chdir'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/runner.rb:45:in `execute'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/lane_manager.rb:56:in `cruise_lane'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/command_line_handler.rb:36:in `handle'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/commands_generator.rb:108:in `block (2 levels) in run'
  /Users/distiller/.gem/ruby/2.4.2/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  /Users/distiller/.gem/ruby/2.4.2/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  /Users/distiller/.gem/ruby/2.4.2/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:75:in `run!'
  /Users/distiller/.gem/ruby/2.4.2/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/commands_generator.rb:337:in `run'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/commands_generator.rb:42:in `start'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/fastlane/lib/fastlane/cli_tools_distributor.rb:94:in `take_off'
  /Users/distiller/.gem/ruby/2.4.2/gems/fastlane-2.76.0/bin/fastlane:20:in `<top (required)>'
  /Users/distiller/.gem/ruby/2.4.2/bin/fastlane:23:in `load'
  /Users/distiller/.gem/ruby/2.4.2/bin/fastlane:23:in `<top (required)>'

### Environment
bundle exec fastlane env
^D^D[⠋] 🚀 [⠙] 🚀 [⠹] 🚀 [⠸] 🚀 [⠼] 🚀 [✔] 🚀 
[12:04:24]: Generating fastlane environment output, this might take a few seconds...
<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                           |
| --------------------------- | ----------------------------------------------- |
| OS                          | 10.12.6                                         |
| Ruby                        | 2.4.2                                           |
| Bundler?                    | true                                            |
| Git                         | git version 2.14.3 (Apple Git-98)               |
| Installation Source         | ~/.gem/ruby/2.4.2/bin/fastlane                  |
| Host                        | Mac OS X 10.12.6 (16G29)                        |
| Ruby Lib Dir                | ~/.rubies/ruby-2.4.2/lib                        |
| OpenSSL Version             | OpenSSL 1.0.2m  2 Nov 2017                      |
| Is contained                | false                                           |
| Is homebrew                 | false                                           |
| Is installed via Fabric.app | false                                           |
| Xcode Path                  | /Applications/Xcode-9.2.app/Contents/Developer/ |
| Xcode Version               | 9.2                                             |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   | en_US.UTF-8 | ✅ |
| LANGUAGE |             |   |

### fastlane files:

<details><summary>`./fastlane/Fastfile`</summary>

```ruby
update_fastlane
default_platform :ios

platform :ios do
  ENV["SLACK_URL"] = "https://hooks.slack.com/services/xxxxx # ios_builds channel

  ENV["MATCH_PASSWORD"] = xxx
  ENV["MATCH_GIT_URL"] = xxx
  ENV["MATCH_READONLY"] = "false"
  ENV["MATCH_VERBOSE"] = "true"

  ENV["GYM_VERBOSE"] = "true"

  ENV["IS_LOCAL"] = "false"
end

desc "Runs all the tests in prod."
lane :test do
  if git_branch == "master"
    scan(scheme: "client") #Will not run UI tests
  else
    uiTestDev
  end
end

desc "Runs UI test in dev"
lane :uiTestDev do
  scan(scheme: "clientDev", devices: ["iPhone X (11.2)"])
end

```
</details>

<details><summary>`./fastlane/Appfile`</summary>

```ruby
app_identifier ENV["APP_IDENTIFIER"]#"com.thing.blah" # The bundle identifier of your app
apple_id "xxxxx" # Your Apple email address

team_id "xxxxxxx"  # Developer Portal Team ID

# you can even provide different app identifiers, Apple IDs and team names per lane:
# More information: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Appfile.md

```
</details>

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.76.0  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

| Plugin                     | Version | Update-Status |
| -------------------------- | ------- | ------------- |
| fastlane-plugin-sentry     | 1.4.1   | ✅ Up-To-Date  |
| fastlane-plugin-s3_actions | 0.1.3   | ✅ Up-To-Date  |

<details><summary><b>Loaded gems</b></summary>

| Gem                        | Version      |
| -------------------------- | ------------ |
| did_you_mean               | 1.1.0        |
| bundler                    | 1.16.0       |
| io-console                 | 0.4.6        |
| CFPropertyList             | 2.3.6        |
| concurrent-ruby            | 1.0.5        |
| i18n                       | 0.9.1        |
| minitest                   | 5.11.1       |
| thread_safe                | 0.3.6        |
| tzinfo                     | 1.2.4        |
| activesupport              | 4.2.10       |
| public_suffix              | 2.0.5        |
| addressable                | 2.5.2        |
| babosa                     | 1.0.2        |
| claide                     | 1.0.2        |
| fuzzy_match                | 2.0.4        |
| nap                        | 1.1.0        |
| cocoapods-core             | 1.3.1        |
| cocoapods-deintegrate      | 1.0.1        |
| cocoapods-downloader       | 1.1.3        |
| cocoapods-plugins          | 1.0.0        |
| cocoapods-search           | 1.0.0        |
| cocoapods-stats            | 1.0.0        |
| netrc                      | 0.11.0       |
| cocoapods-trunk            | 1.3.0        |
| cocoapods-try              | 1.1.0        |
| colored2                   | 3.1.2        |
| escape                     | 0.0.4        |
| fourflusher                | 2.0.1        |
| gh_inspector               | 1.0.3        |
| molinillo                  | 0.5.7        |
| ruby-macho                 | 1.1.0        |
| nanaimo                    | 0.2.3        |
| xcodeproj                  | 1.5.4        |
| cocoapods                  | 1.3.1        |
| colored                    | 1.2          |
| highline                   | 1.7.10       |
| commander-fastlane         | 4.4.5        |
| declarative                | 0.0.10       |
| declarative-option         | 0.1.0        |
| unf_ext                    | 0.0.7.4      |
| unf                        | 0.1.4        |
| domain_name                | 0.5.20170404 |
| dotenv                     | 2.2.1        |
| excon                      | 0.60.0       |
| multipart-post             | 2.0.0        |
| faraday                    | 0.13.1       |
| http-cookie                | 1.0.3        |
| faraday-cookie_jar         | 0.0.6        |
| faraday_middleware         | 0.12.2       |
| fastimage                  | 2.1.1        |
| jwt                        | 2.1.0        |
| little-plugger             | 1.1.4        |
| multi_json                 | 1.13.1       |
| logging                    | 2.2.2        |
| memoist                    | 0.16.0       |
| os                         | 0.9.6        |
| signet                     | 0.8.1        |
| googleauth                 | 0.6.2        |
| httpclient                 | 2.8.3        |
| mime-types-data            | 3.2016.0521  |
| mime-types                 | 3.1          |
| uber                       | 0.1.0        |
| representable              | 3.0.4        |
| retriable                  | 3.1.1        |
| google-api-client          | 0.13.6       |
| json                       | 2.1.0        |
| mini_magick                | 4.5.1        |
| multi_xml                  | 0.6.0        |
| plist                      | 3.4.0        |
| rubyzip                    | 1.2.1        |
| security                   | 0.1.3        |
| slack-notifier             | 2.3.2        |
| terminal-notifier          | 1.8.0        |
| unicode-display_width      | 1.3.0        |
| terminal-table             | 1.8.0        |
| tty-screen                 | 0.6.4        |
| tty-cursor                 | 0.5.0        |
| tty-spinner                | 0.8.0        |
| word_wrap                  | 1.0.0        |
| rouge                      | 2.0.7        |
| xcpretty                   | 0.2.8        |
| xcpretty-travis-formatter  | 1.0.0        |
| proxies                    | 0.2.3        |
| s3                         | 0.3.26       |
| fastlane-plugin-s3_actions | 0.1.3        |
| fastlane-plugin-sentry     | 1.4.1        |
| rest-client                | 2.0.2        |
</details>

*generated on:* **2018-01-16**

**Comment by KrauseFx** [comment]
Thanks for the report, also just got https://github.com/fastlane/fastlane/pull/11446#issuecomment-358063290

**Comment by KrauseFx** [comment]
Thanks for reporting this, we'll try to fix this as soon as possible

**Comment by MaximusMcCann** [comment]
Cheeers!

**Comment by KrauseFx** [comment]
Update scan test result poster to use new slack API: https://github.com/fastlane/fastlane/pull/11591

**Comment by KrauseFx** [comment]
@taquitos will be shipping a new release shorty

**Comment by taquitos** [comment]
🎈:goat: release shipped 🎉

**Comment by taquitos** [comment]
Closing the issue, but let us know if you have any problems!
