### ISSUE TITLE
undefined method `all_build_train_numbers' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by anback** [fastlane/fastlane#3997]
### New Issue Checklist

- [x ] Updated fastlane to the latest version
- [ x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description
 download_dsysm failed when updating fastlane to 1.68

##### Complete output when running fastlane, including the stack trace and command used

```
/Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/download_dsyms.rb:19:in `run': [!] 
> undefined method `all_build_train_numbers' for nil:NilClass (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:143:in `block (2 levels) in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/actions/actions_helper.rb:35:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:129:in `block in execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:128:in `execute_action'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:149:in `method_missing'
	from Fastfile:29:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:110:in `try_switch_to_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:141:in `rescue in method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/fast_file.rb:136:in `method_missing'
	from Fastfile:38:in `block (2 levels) in parsing_binding'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane.rb:36:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:52:in `block in execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `chdir'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/runner.rb:46:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/lane_manager.rb:46:in `cruise_lane'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/lib/fastlane/command_line_handler.rb:30:in `handle'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:38:in `block (2 levels) in run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane_core-0.41.0/lib/fastlane_core/ui/fastlane_runner.rb:23:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:156:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/fastlane-1.68.0/bin/fastlane:162:in `<top (required)>'
	from /usr/local/bin/fastlane:23:in `load'
	from /usr/local/bin/fastlane:23:in `<main>'
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby
  lane :upload do
    download_dsyms
    upload_symbols_to_crashlytics(binary_path: "./ios/Crashlytics.framework/uploadDSYM")
  end

```

### Environment

fastlane version (fastlane -v): fastlane 1.68.0
Do you use bundler, rbenv or rvm? no bundler

**Comment by TKBurner** [comment]
@anback Thanks for reaching out. We are looking into this! :+1:  Does this happen when you run 'fastlane run download_dsyms'?

**Comment by anback** [comment]
yep, 

just ran it



Cheers

**Comment by anback** [comment]
![image](https://cloud.githubusercontent.com/assets/2440382/14180873/234ee334-f765-11e5-82e7-f7e0d7354272.png)

**Comment by ohwutup** [comment]
Hey @anback I am going to close this issue as it appears to have been fixed in recent releases. Please feel free to reopen the issue if you are still running into issues! 🐙
