### ISSUE TITLE
fastlane supply fails with error "NoMethodError: [!] undefined method `map' for nil:NilClass"

### ISSUE THREAD

**Issue by trevoriancox** [fastlane/fastlane#10033]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)
- [x] I read [docs.fastlane.tools](https://docs.fastlane.tools)
- [x] I searched for [existing GitHub issues](https://github.com/fastlane/fastlane/issues)

### Issue Description

This command worked yesterday but fails today. 

```
`bundler exec fastlane supply --track beta --json_key ./appazur-build.json --skip_upload_screenshots --package_name com.... --apk .../com.....apk --skip_upload_apk`

+-------------------------+----------------------------------------------------------------------+
|                                   Summary for supply 2.53.1                                    |
+-------------------------+----------------------------------------------------------------------+
| track                   | beta                                                                 |
| json_key                | ./appazur-build.json                                                 |
| skip_upload_screenshots | true                                                                 |
| package_name            | com.appazur...                                         |
| apk                     | .../bin/Release/com.appazur.....apk |
| skip_upload_apk         | true                                                                 |
| metadata_path           | ./fastlane/metadata/android                                          |
| skip_upload_metadata    | false                                                                |
| skip_upload_images      | false                                                                |
| validate_only           | false                                                                |
| check_superseded_tracks | false                                                                |
+-------------------------+----------------------------------------------------------------------+

[12:22:49]: Preparing to upload for language 'en-US'...
[12:22:49]: Uploading image file ./fastlane/metadata/android/en-US/images/featureGraphic.png...
[12:22:51]: Uploading image file ./fastlane/metadata/android/en-US/images/icon.png...
[12:22:53]: Uploading image file ./fastlane/metadata/android/en-US/images/promoGraphic.png...

Looking for related GitHub issues on fastlane/fastlane...

➡️  Crash on registering device UDID
    https://github.com/fastlane/fastlane/issues/8106 [closed] 3 💬
    30 May 2017

➡️  fastlane reporting apple developer website is down
    https://github.com/fastlane/fastlane/issues/5918 [closed] 19 💬
    06 Dec 2016

➡️  deliver fails to save screenshots with "must be a .jpeg, .jpg, or .png (...)"
    https://github.com/fastlane/fastlane/issues/6426 [closed] 17 💬
    04 Jan 2017

🔗  You can ⌘ + double-click on links to open them directly in your browser.
bundler: failed to load command: fastlane (.../.bundle/ruby/2.3.0/bin/fastlane)
NoMethodError: [!] undefined method `map' for nil:NilClass
Did you mean?  tap
Did you mean?  tap
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/client.rb:164:in `apks_version_codes'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/uploader.rb:50:in `upload_changelogs'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/uploader.rb:22:in `block in perform_upload'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/uploader.rb:13:in `each'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/uploader.rb:13:in `perform_upload'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/commands_generator.rb:38:in `block (2 levels) in run'
  .../.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:178:in `call'
  .../.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/command.rb:153:in `run'
  .../.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/runner.rb:476:in `run_active_command'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane_core/lib/fastlane_core/ui/fastlane_runner.rb:64:in `run!'
  .../.bundle/ruby/2.3.0/gems/commander-fastlane-4.4.5/lib/commander/delegates.rb:15:in `run!'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/commands_generator.rb:59:in `run'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/supply/lib/supply/commands_generator.rb:12:in `start'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/fastlane/lib/fastlane/cli_tools_distributor.rb:58:in `take_off'
  .../.bundle/ruby/2.3.0/gems/fastlane-2.53.1/bin/fastlane:20:in `<top (required)>'
  .../.bundle/ruby/2.3.0/bin/fastlane:23:in `load'
  .../.bundle/ruby/2.3.0/bin/fastlane:23:in `<top (required)>'

Fatal error: local() encountered an error (return code 1) while executing 'bundler exec fastlane supply --track beta --json_key ./appazur-build.json --skip_upload_screenshots --package_name com.. --apk ..../bin/Release/com...._final.apk --skip_upload_apk'

Aborting.
local() encountered an error (return code 1) while executing 'bundler exec fastlane supply --track beta --json_key ./appazur-build.json --skip_upload_screenshots --package_name com.... --apk ..._final.apk --skip_upload_apk'
```

### Environment

<details><summary>✅ fastlane environment ✅</summary>

### Stack

| Key                         | Value                                                              |
| --------------------------- | ------------------------------------------------------------------ |
| OS                          | 10.12.4                                                            |
| Ruby                        | 2.3.1                                                              |
| Bundler?                    | true                                                               |
| Git                         | git version 2.11.0 (Apple Git-81)                                  |
| Installation Source         | ~/.../.bundle/ruby/2.3.0/bin/fastlane |
| Host                        | Mac OS X 10.12.4 (16E195)                                          |
| Ruby Lib Dir                | ~/.rbenv/versions/2.3.1/lib                                        |
| OpenSSL Version             | OpenSSL 1.0.2k  26 Jan 2017                                        |
| Is contained                | false                                                              |
| Is homebrew                 | false                                                              |
| Is installed via Fabric.app | false                                                              |
| Xcode Path                  | /Applications/Xcode.app/Contents/Developer/                        |
| Xcode Version               | 8.3.2                                                              |

### System Locale

| Variable | Value       |   |
| -------- | ----------- | - |
| LANG     | en_US.UTF-8 | ✅ |
| LC_ALL   |             |   |
| LANGUAGE |             |   |

### fastlane files:

**No Fastfile found**

**No Appfile found**

### fastlane gems

| Gem      | Version | Update-Status |
| -------- | ------- | ------------- |
| fastlane | 2.53.1  | ✅ Up-To-Date  |

### Loaded fastlane plugins:

**No plugins Loaded**

<details><summary><b>Loaded gems</b></summary>

| Gem                       | Version      |
| ------------------------- | ------------ |
| did_you_mean              | 1.0.0        |
| bundler                   | 1.14.6       |
| io-console                | 0.4.6        |
| CFPropertyList            | 2.3.5        |
| public_suffix             | 2.0.5        |
| addressable               | 2.5.1        |
| babosa                    | 1.0.2        |
| claide                    | 1.0.2        |
| colored                   | 1.2          |
| colored2                  | 3.1.2        |
| highline                  | 1.7.8        |
| commander-fastlane        | 4.4.5        |
| declarative               | 0.0.9        |
| declarative-option        | 0.1.0        |
| unf_ext                   | 0.0.7.4      |
| unf                       | 0.1.4        |
| domain_name               | 0.5.20170404 |
| dotenv                    | 2.2.1        |
| excon                     | 0.58.0       |
| multipart-post            | 2.0.0        |
| faraday                   | 0.12.2       |
| http-cookie               | 1.0.3        |
| faraday-cookie_jar        | 0.0.6        |
| faraday_middleware        | 0.12.2       |
| fastimage                 | 2.1.0        |
| gh_inspector              | 1.0.3        |
| jwt                       | 1.5.6        |
| little-plugger            | 1.1.4        |
| multi_json                | 1.12.1       |
| logging                   | 2.2.2        |
| memoist                   | 0.16.0       |
| os                        | 0.9.6        |
| signet                    | 0.7.3        |
| googleauth                | 0.5.3        |
| httpclient                | 2.8.3        |
| mime-types-data           | 3.2016.0521  |
| mime-types                | 3.1          |
| uber                      | 0.1.0        |
| representable             | 3.0.4        |
| retriable                 | 3.1.1        |
| google-api-client         | 0.12.0       |
| json                      | 2.1.0        |
| mini_magick               | 4.5.1        |
| multi_xml                 | 0.6.0        |
| plist                     | 3.3.0        |
| rubyzip                   | 1.2.1        |
| security                  | 0.1.3        |
| slack-notifier            | 1.5.1        |
| terminal-notifier         | 1.8.0        |
| unicode-display_width     | 1.3.0        |
| terminal-table            | 1.8.0        |
| tty-screen                | 0.5.0        |
| word_wrap                 | 1.0.0        |
| nanaimo                   | 0.2.3        |
| xcodeproj                 | 1.5.1        |
| rouge                     | 2.0.7        |
| xcpretty                  | 0.2.8        |
| xcpretty-travis-formatter | 0.0.4        |
</details>

*generated on:* **2017-08-11**
</details>

**Comment by trevoriancox** [comment]
Resolved my deleting my Gemfile.lock and bin folder and reinstalling.

**Comment by trevoriancox** [comment]
Reinstalling did not resolve the issue (deleted all gems and reinstalled).
Tried fastlane 2.52.0, 2.53.0, and 2.53.1 with same result.

With fastlane 2.54.0.beta.20170816010003, error is "undefined method `get_edit_listing'"

**Comment by trevoriancox** [comment]
In `apks_version_codes`, the returned object from the Google API is used without testing that the apks value is not null:

```
      result = call_google_api { android_publisher.list_edit_apks(current_package_name, current_edit.id) }
      return result.apks.map(&:version_code)
```

**Comment by jacks205** [comment]
I am getting the same issue on Fastlane version `2.54.0` when running `supply`

**Comment by inidona** [comment]
hi, i have already the same problem with Fastlane version 2.54.0 when uploading to alpha

**Comment by vdelricco** [comment]
Similar problem here:

`
/home/ubuntu/.rvm/gems/ruby-2.3.0/gems/fastlane-2.54.0/supply/lib/supply/client.rb:145:in 'listing_for_language': [!] undefined method 'get_edit_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x00000003c06c48> (NoMethodError)
`

I can provide more of the log file if necessary.

**Comment by meyskens** [comment]
Same issue here
```
/home/travis/.rvm/gems/ruby-2.4.1/gems/fastlane-2.54.0/supply/lib/supply/client.rb:145:in `listing_for_language': [!] undefined method `get_edit_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x00000004446228> (NoMethodError)

Did you mean?  get_apk_listing

Did you mean?  get_apk_listing
```

**Comment by tejasna** [comment]
Same issue after updating to 25.4.0 
````
/.rvm/gems/ruby-2.4.1/gems/fastlane-2.54.0/supply/lib/supply/client.rb:145:in `listing_for_language': [!] undefined method `get_edit_listing' for #<Google::Apis::AndroidpublisherV2::AndroidPublisherService:0x007fd20ad950b0> (NoMethodError)
Did you mean?  get_apk_listing
````

**Comment by mpirri** [comment]
We just merged #10120 to fix this issue and will be making a `fastlane` release shorty!  Thanks for your patience, and we're sorry for the inconvenience!  🚀

**Comment by meyskens** [comment]
Confirmed that it works in `2.55.0.beta.20170824010002`

**Comment by jtroest** [comment]
It is still missing one spot: [10137](https://github.com/fastlane/fastlane/pull/10137)

**Comment by sampsakuronen** [comment]
I managed to fix this in my case by adding a dummy alpha-channel release with a hand-built APK.

We didn't have any app releases in the Play store. I think this is why some API call returned something unexpected to `supply`.

**Comment by joncursi** [comment]
I still have this issue on `2.56.0` when uploading metadata during `supply`:

```
...
[05:08:45]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/feed.png...
[05:08:47]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/project-about.png...
[05:08:49]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tenInchScreenshots/project.png...
[05:08:52]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tvScreenshots/feed.png...
[05:08:55]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tvScreenshots/project-about.png...
[05:08:59]: Uploading screenshot ./fastlane/metadata/android/en-US/images/tvScreenshots/project.png...
...
undefined method `map' for nil:NilClass
```

**Comment by joncursi** [comment]
I was also able to get by this by uploading a dummy build to my `Beta` channel, which was previously empty
