### ISSUE TITLE
Screengrab issue on Circle-Ci

### ISSUE THREAD

**Issue by joeabouassi** [fastlane/fastlane#4500]
### New Issue Checklist

- [x] Updated fastlane to the latest version
- [x] I have read the [Contribution Guidelines](https://github.com/fastlane/fastlane/blob/master/CONTRIBUTING.md)

### Issue Description

When running screengrab command on Circle-Ci through fastlane's fastfile I get a list of "No such file or directory" for all project files.
Circle-Ci link to the build: https://circleci.com/gh/joeabouassi/TestAppGithub/84

##### Complete output when running fastlane, including the stack trace and command used

```
bundle exec fastlane deploy
/home/ubuntu/TestAppGithub/gems/ruby/2.3.0/gems/commander-4.3.5/lib/commander/user_interaction.rb:334: warning: constant ::TimeoutError is deprecated
[08:23:06]: Your Fastfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.
[08:23:06]: -------------------------------------------------
[08:23:06]: --- Step: Verifying required fastlane version ---
[08:23:06]: -------------------------------------------------
[08:23:06]: fastlane version valid
[08:23:06]: Driving the lane 'deploy' 🚀
[08:23:06]: current: /home/ubuntu/TestAppGithub/fastlane
[08:23:06]: ------------------------
[08:23:06]: --- Step: screengrab ---
[08:23:06]: ------------------------

+-----------------------------+--------------------------------------------------------------------+
|                                   Summary for screengrab 0.3.2                                   |
+-----------------------------+--------------------------------------------------------------------+
| locales                     | ["en-US"]                                                          |
| clear_previous_screenshots  | true                                                               |
| app_apk_path                | /home/ubuntu/TestAppGithub/app/build/outputs/apk/app-debug.apk     |
| tests_apk_path              | /home/ubuntu/TestAppGithub/app/build/outputs/apk/app-debug-unal... |
| output_directory            | /home/ubuntu/TestAppGithub/fastlane/metadata/android               |
| tests_package_name          | com.eurisko.testappgithub.test                                     |
| android_home                | /usr/local/android-sdk-linux                                       |
| skip_open_summary           | true                                                               |
| app_package_name            | com.eurisko.testappgithub                                          |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner                     |
| ending_locale               | en-US                                                              |
| device_type                 | phone                                                              |
+-----------------------------+--------------------------------------------------------------------+

[08:23:06]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[08:23:06]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[08:23:06]: Clearing phoneScreenshots within /home/ubuntu/TestAppGithub/fastlane/metadata/android
[08:23:06]: $ adb devices -l
[08:23:06]: ▸ List of devices attached
[08:23:06]: ▸ * daemon not running. starting it now on port 5037 *
[08:23:06]: ▸ * daemon started successfully *
[08:23:09]: ▸ emulator-5554          device product:sdk model:sdk device:generic
[08:23:09]: $ adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE
[08:23:09]: ▸ * daemon not running. starting it now on port 5037 *
[08:23:09]: ▸ * daemon started successfully *
[08:23:12]: ▸ /storage/sdcard
[08:23:12]: Cleaning screenshots on device
* daemon not running. starting it now on port 5037 *
* daemon started successfully *
Gemfile: No such file or directory
Gemfile.lock: No such file or directory
app: No such file or directory
build: No such file or directory
build.gradle: No such file or directory
circle.yml: No such file or directory
fastlane: No such file or directory
gems: No such file or directory
gradle: No such file or directory
gradle-2.10: No such file or directory
gradle-2.10-bin.zip: No such file or directory
gradle.properties: No such file or directory
gradlew: No such file or directory
gradlew.bat: No such file or directory
keys.json: No such file or directory
nohup.out: No such file or directory
scripts: No such file or directory
settings.gradle: No such file or directory
testkeystore.jks: No such file or directory
daemon: No such file or directory
not: No such file or directory
running.: No such file or directory
starting: No such file or directory
it: No such file or directory
now: No such file or directory
on: No such file or directory
port: No such file or directory
5037: No such file or directory
Gemfile: No such file or directory
Gemfile.lock: No such file or directory
app: No such file or directory
build: No such file or directory
build.gradle: No such file or directory
circle.yml: No such file or directory
fastlane: No such file or directory
gems: No such file or directory
gradle: No such file or directory
gradle-2.10: No such file or directory
gradle-2.10-bin.zip: No such file or directory
gradle.properties: No such file or directory
gradlew: No such file or directory
gradlew.bat: No such file or directory
keys.json: No such file or directory
nohup.out: No such file or directory
scripts: No such file or directory
settings.gradle: No such file or directory
testkeystore.jks: No such file or directory
sh: 2: Gemfile: not found
sh: 3: /storage/sdcard/com.eurisko.testappgithub/screengrab: not found
[08:23:15]: Exit status: 127
[08:23:15]: Variable Dump:
[08:23:15]: {:PLATFORM_NAME=>nil, :LANE_NAME=>"deploy"}
[08:23:15]: Exit status: 127

+------+-------------------------------------+-------------+
|                     fastlane summary                     |
+------+-------------------------------------+-------------+
| Step | Action                              | Time (in s) |
+------+-------------------------------------+-------------+
| 1    | Verifying required fastlane version | 0           |
| 2    | screengrab                          | 9           |
+------+-------------------------------------+-------------+

[08:23:15]: fastlane finished with errors

[!] Exit status: 127

bundle exec fastlane deploy returned exit code 1

Action failed: bundle exec fastlane deploy
```

### Configuration Files

Please copy the complete content of your `Fastfile` and any other configuration files you use below:

Fastfile:
```ruby

require 'fileutils'

fastlane_version "1.84.0"

lane :deploy do 
  puts "current: " + Dir.pwd

  #Screenshots
  screengrab(
    verbose: true,
    locales: ['en-US'],
    clear_previous_screenshots: true,
    app_apk_path: '/home/ubuntu/TestAppGithub/app/build/outputs/apk/app-debug.apk',
    tests_apk_path: '/home/ubuntu/TestAppGithub/app/build/outputs/apk/app-debug-unaligned.apk',
    output_directory: '/home/ubuntu/TestAppGithub/fastlane/metadata/android'
  )
  
  #Upload to Google Play 
  supply( 
    track: "production",
    apk: '/home/ubuntu/TestAppGithub/app/build/outputs/apk/app-release.apk'
  ) 

end
```

### Environment

fastlane version (run `fastlane -v`): 1.84.0

Do you use bundler to execute fastlane (i.e. `bundle exec fastlane`)? yes

Do you use a Ruby environment manager (e.g. `chruby`, `rbenv`, `rvm`)? rvm

**Comment by TKBurner** [comment]
Hi @joeabouassi! Great to hear from you. Are you able to run this command?

adb -s emulator-5554 shell echo \$EXTERNAL_STORAGE

It looks like that is where you are seeing the failure. Thanks!

**Comment by joeabouassi** [comment]
hi @TKBurner, the command works on its own and prints "/storage/sdcard" before calling bundle exec fastlane deploy.
I'm assuming it has something to do with the path in which screengrab is being executed, because it works on my local macbook pro (circle-ci uses a linux VM for android). 
I couldnt install fastlane using "sudo gem install" so instead I used gem install for it to work and I even tried supply on its own and it worked on circle-ci by uploading the apk to the play store.

**Comment by joeabouassi** [comment]
I installed fastlane by using sudo on circle-ci and re-ran screengrab command with no luck, still gives the same "No such file or directory" error for all project files. @TKBurner

**Comment by TKBurner** [comment]
@joeabouassi Thanks for following up. Can you try setting the android_home value and build_tools_version? It looks like we are having an issue running gradle. Let me know how it goes!

**Comment by joeabouassi** [comment]
@TKBurner Ive set both values accordingly (23.0.2 and  /usr/local/android-sdk-linux) same error occurred.
I also switched to Travis-Ci and tried the whole procedure, it got me another error this time:

```
/home/travis/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.43.1/lib/fastlane_core/command_executor.rb:79:in `execute': [!] undefined method `exitstatus' for nil:NilClass (NoMethodError)
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/lib/screengrab/runner.rb:80:in `select_device'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/lib/screengrab/runner.rb:52:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/bin/screengrab:39:in `block (2 levels) in run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.43.1/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/bin/screengrab:56:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/bin/screengrab:62:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/screengrab:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/screengrab:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
The command "screengrab" failed and exited with 1 during .

```

First I tried installing fastlane and running screengrab, then I tried installing screengrab alone, both cases produced the same error. although it worked once by mistake while fixing a path issue with supply and after that I keep getting the above error.

Thank you for your cooperation.

**Comment by joeabouassi** [comment]
While searching for similar issues I found the following: [https://github.com/fastlane/fastlane/issues/2077](url)
I reverted to fastlane_core version 0.38.0 while also reverting supply to version 0.5.2 (coz the latest version required fastlane_core >= 0.40.0) which fixed the issue and screengrab worked.
The issue mentioned earlier was closed, but it seems that it hasn't been completely fixed.
@TKBurner

**Comment by TKBurner** [comment]
Hi @joeabouassi Thanks for following up. To confirm if you run fastlane run update_fastlane, your screengrab will get the error again? Which specific error are you getting at this point. Thanks! 👍

**Comment by joeabouassi** [comment]
@TKBurner update_fastlane has no effect coz fastlane will be installed each time the build runs using gem install fastlane which downloads the latest version of all gems. I get the same error:

```
$ screengrab
+-----------------------------+-----------------------------------------------------------+
|                              Summary for screengrab 0.3.2                               |
+-----------------------------+-----------------------------------------------------------+
| tests_package_name          | com.eurisko.testappgithub.test                            |
| android_home                | /usr/local/android-sdk/                                   |
| locales                     | ["en-US"]                                                 |
| clear_previous_screenshots  | false                                                     |
| output_directory            | fastlane/metadata/android                                 |
| skip_open_summary           | true                                                      |
| app_package_name            | com.eurisko.testappgithub                                 |
| test_instrumentation_runner | android.support.test.runner.AndroidJUnitRunner            |
| ending_locale               | en-US                                                     |
| app_apk_path                | app/build/outputs/apk/app-debug.apk                       |
| tests_apk_path              | app/build/outputs/apk/app-debug-androidTest-unaligned.apk |
| device_type                 | phone                                                     |
+-----------------------------+-----------------------------------------------------------+
[09:14:46]: Limiting the test classes run by `screengrab` to just those that generate screenshots can make runs faster.
[09:14:46]: Consider using the :use_tests_in_classes or :use_tests_in_packages option, and organize your tests accordingly.
[09:14:46]: $ adb devices -l
[09:14:46]: ▸ List of devices attached
[09:14:46]: ▸ emulator-5554          device product:sdk model:sdk device:generic
-------------------------------------------------------------------------------------------
  An error occured. Please enable crash reports using `fastlane enable_crash_reporting`.
  This makes resolving issues much easier and helps improve fastlane.
  The reports will be stored securely on getsentry.com.
  More information about privacy: https://github.com/fastlane/fastlane/releases/tag/1.33.3
-------------------------------------------------------------------------------------------
/home/travis/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.43.2/lib/fastlane_core/command_executor.rb:79:in `execute': [!] undefined method `exitstatus' for nil:NilClass (NoMethodError)
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/lib/screengrab/runner.rb:80:in `select_device'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/lib/screengrab/runner.rb:52:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/bin/screengrab:39:in `block (2 levels) in run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/command.rb:178:in `call'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/command.rb:153:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/runner.rb:428:in `run_active_command'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/fastlane_core-0.43.2/lib/fastlane_core/ui/fastlane_runner.rb:26:in `run!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/commander-4.3.5/lib/commander/delegates.rb:15:in `run!'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/bin/screengrab:56:in `run'
	from /home/travis/.rvm/gems/ruby-2.3.1/gems/screengrab-0.3.2/bin/screengrab:62:in `<top (required)>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/screengrab:23:in `load'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/screengrab:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
	from /home/travis/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by TKBurner** [comment]
@joeabouassi Thanks for working with me on this. I just reached out to the rest of the core team to get some more eyes on this. We'll follow up on this thread. Hope that you have a wonderful day! 👍

**Comment by joeabouassi** [comment]
Thank you for your cooperation @TKBurner !

**Comment by i2amsam** [comment]
@joeabouassi Thanks for the detail report! 💯 . I just shipped an update to `fastlane_core 0.43.5` which puts the old fix back in, could you give it a try and let me know if that works?  Thanks!

**Comment by joeabouassi** [comment]
Hi @i2amsam! Thank you for providing that update to fastlane_core! Everything worked perfectly now with the latest version of fastlane.
Although this solves it on TravisCI, it doesn't have any effect on CircleCI, there has to be something else which causes those "No such file or directory" messages. 
I guess we'll be sticking with TravisCI for the time being.

Best Regards!

**Comment by i2amsam** [comment]
Huzzah! 👍 Hrm, I'm not sure about the circle problem, there was another ticket I looked at the other day where circle was behaving differently, have a look at https://github.com/fastlane/fastlane/issues/4525 . I think that they may be pre-packaging old versions somehow.  I'll close this issue as we got at least a partial fix, but feel free to re-open a new one if you think it's a fastlane problem.
